const fs = require('fs');
// ku_chunk1.js — first 32 keys (Brand/Shell, Notes Manager)
const M = {};
M.eyebrow = '';
M.title = 'EQ7';
M.install = 'لە سەر بەرنامەدا تێپەڕەوە';
M.actions = 'فەرموێنەکان';
M.notesManagerTitle = 'بازرگای نۆتەکان';
M.notesManagerSubtitle = 'نۆتەکان لە فۆلدرەکاندا بەرزەوە و ئەکەنەرێکی تەواوی لمە بکەرەوە.';
M.foldersTitle = 'فۆلدرەکان';
M.addFolder = '+ فۆلدر';
M.newNoteButton = 'نۆتەی تەواوی لمە';
M.notesTitle = 'نۆتەکان';
M.refreshNotes = 'تازەکردەوە';
M.fullScreenNoteTitle = 'نۆتەی تەواوی لمە';
M.noteFolderLabel = 'فۆلدر';
M.noteTitleLabel = 'ناونیشان';
M.noteTitlePlaceholder = 'ناونیشانی نۆتە';
M.folderSelectLabel = 'فۆلدر';
M.noteBodyPlaceholder = 'دەست بە نووسینیت...';
M.noteTableInsertPopupTitle = 'خۆشی خشتە چاپ بکە';
M.noteHeadingMenuLabel = 'غرێب';
M.noteHeading1Label = 'غرێب ١';
M.noteHeading2Label = 'غرێب ٢';
M.noteHeading3Label = 'غرێب ٣';
M.noteNormalTextLabel = 'دەقێکی ئاسایی';
M.noteTableRowsLabel = 'ڕێژەکان';
M.noteTableColsLabel = 'ستۆکان';
M.noteTableHeaderRowLabel = 'ڕێژەی سەرەکی سیڕی';
M.noteTableInsertBtnLabel = 'خۆشی خشتە چاپ بکە';
M.noteImageLabel = 'وێنە';
M.noteImageUpload = 'دامەزراندن';
M.noteImageCamera = 'کەمێرە';
M.noteTablePresetCustomLabel = 'خۆشەhati';
M.untitled = 'تەواوی لمە';
fs.writeFileSync('__phase37b/ku_map.json', JSON.stringify(M, null, 2), 'utf8');
console.log('chunk1 OK: ' + Object.keys(M).length + ' keys');
