// P40 sci checks A
import { boot } from './__p40_harness.mjs';
const { page, server, browser, errs, sleep } = await boot(8240);
const out = [];
const check = (n, ok, d = '') => { out.push({ n, ok }); console.log(`${ok ? 'PASS' : 'FAIL'}  ${n}${d ? ' -> ' + d : ''}`); };
const tap = (s) => page.evaluate((x) => { document.querySelector(x).click(); }, s);
const read = () => page.evaluate(() => ({ d: document.querySelector('#primaryDisplay').textContent, e: document.querySelector('#expressionDisplay').textContent, w: document.querySelector('#secondaryDisplay').textContent, o: document.querySelector('#scientificPanel').classList.contains('open') }));
const num = (x) => tap(`.keypad-btn.number[data-value="${x}"]`);
const op = (x) => tap(`.keypad-btn.operator[data-value="${x}"]`);
const eq = () => tap('.keypad-btn.equals');
const clear = () => tap('.control-btn[data-action="clear"]');
const sci = (v) => page.evaluate((x) => { [...document.querySelectorAll('.scientific-btn')].find((q) => q.getAttribute('data-scientific') === x).click(); }, v);
const tn = async (s) => { for (const c of s) await num(c); };
const ap = (a, b) => Math.abs(parseFloat(String(a).replace(/,/g, '')) - b) < 5e-5;
await tap('#scientificToggle'); await sleep(150);
let r = await read();
check('opens', r.o === true);
check('11 btns', await page.evaluate(() => document.querySelectorAll('.scientific-btn').length) === 11);
await clear(); await tn('2'); await sci('^'); await tn('3'); await eq(); r = await read();
check('2^3=8', r.d === '8', r.d + '|' + r.w);
await clear(); await tn('5'); await sci('^'); await tn('2'); await eq(); r = await read();
check('5^2=25', r.d === '25', r.d);
await clear(); await tn('9'); await sci('^'); await tn('0.5'); await eq(); r = await read();
check('9^0.5=3', r.d === '3', r.d);
await clear(); await tn('2'); await sci('^'); await sci('('); await op('-'); await tn('2'); await sci(')'); await eq(); r = await read();
check('2^-2=0.25', r.d === '0.25', r.d);
await clear(); await sci('('); await tn('2'); await op('+'); await tn('3'); await sci(')'); await sci('^'); await tn('2'); await eq(); r = await read();
check('(2+3)^2=25', r.d === '25', r.d);
await clear(); await tn('2'); await sci('reciprocal'); await eq(); r = await read();
check('1/2', r.d === '0.5', r.d);
await clear(); await tn('4'); await sci('reciprocal'); await eq(); r = await read();
check('1/4', r.d === '0.25', r.d);
await clear(); await tn('0'); await sci('reciprocal'); await eq(); r = await read();
check('1/0 existing-div0-behavior', /error/i.test(r.d) || r.d === '0', r.d + ' (existing div0 behavior)');
await clear(); await tn('5'); await sci('negate'); await eq(); r = await read();
check('neg5', r.d === '-5', r.d);
await clear(); await sci('pi'); await eq(); r = await read();
check('pi', ap(r.d, Math.PI), r.d);
await clear(); await tn('2'); await sci('pi'); await eq(); r = await read();
check('2pi', ap(r.d, 2 * Math.PI), r.d);
await clear(); await sci('e'); await eq(); r = await read();
check('e', ap(r.d, Math.E), r.d);
const f = out.filter((x) => !x.ok).length;
console.log('FAILS ' + f);
await browser.close(); server.close();
process.exit(f ? 1 : 0);
