// P40 checks B: factorial/percent/regression/backspace/history/responsive/rtl
import { boot } from './__p40_harness.mjs';
const { page, server, browser, errs, sleep } = await boot(8241);
const check = (n, ok, d = '') => console.log(`${ok ? 'PASS' : 'FAIL'}  ${n}${d ? ' -> ' + d : ''}`);
let fails = 0;
const C = (n, ok, d = '') => { check(n, ok, d); if (!ok) fails++; };
const tap = (s) => page.evaluate((x) => { document.querySelector(x).click(); }, s);
const read = () => page.evaluate(() => ({ d: document.querySelector('#primaryDisplay').textContent, e: document.querySelector('#expressionDisplay').textContent, w: document.querySelector('#secondaryDisplay').textContent, h: document.querySelector('#historyList') ? document.querySelector('#historyList').textContent : '', dir: document.documentElement.dir }));
const num = (x) => tap(`.keypad-btn.number[data-value="${x}"]`);
const op = (x) => tap(`.keypad-btn.operator[data-value="${x}"]`);
const eq = () => tap('.keypad-btn.equals');
const clear = () => tap('.control-btn[data-action="clear"]');
const bs = () => tap('.control-btn[data-action="backspace"]');
const sci = (v) => page.evaluate((x) => { [...document.querySelectorAll('.scientific-btn')].find((q) => q.getAttribute('data-scientific') === x).click(); }, v);
const tn = async (s) => { for (const c of s) await num(c); };
await tap('#scientificToggle'); await sleep(150);
let r;
await clear(); await tn('5'); await sci('!'); await eq(); r = await read();
C('5!=120', r.d === '120', r.d + '|' + r.w);
C('5! words', /hundred/i.test(r.w), r.w);
await clear(); await tn('0'); await sci('!'); await eq(); r = await read();
C('0!=1', r.d === '1', r.d);
await clear(); await tn('10'); await sci('!'); await eq(); r = await read();
C('10!', r.d.replace(/,/g, '') === '3628800', r.d);
await clear(); await sci('('); await tn('5'); await sci('negate'); await sci(')'); await sci('!'); await eq(); r = await read();
C('(-5)! err', /error/i.test(r.d), r.d);
await clear(); await tn('5.5'); await sci('!'); await eq(); r = await read();
C('5.5! err', /error/i.test(r.d), r.d);
await clear(); await tn('200'); await sci('!'); await eq(); r = await read();
C('200! guarded', /error/i.test(r.d), r.d);
await clear(); await tn('50'); await sci('%'); await eq(); r = await read();
C('50%', r.d === '0.5', r.d);
await clear(); await tn('25'); await sci('%'); await eq(); r = await read();
C('25%', r.d === '0.25', r.d);
await clear(); await tn('200'); await op('*'); await tn('10'); await sci('%'); await eq(); r = await read();
C('200*10%', r.d === '20', r.d + ' e=' + r.e);
await clear(); await sci('sqrt('); await tn('9'); await sci(')'); await eq(); r = await read();
C('sqrt9', r.d === '3', r.d);
await clear(); await sci('sqrt('); await tn('2.25'); await sci(')'); await eq(); r = await read();
C('sqrt2.25', r.d === '1.5', r.d);
await clear(); await sci('sqrt('); await tn('9'); await op('+'); await tn('7'); await sci(')'); await eq(); r = await read();
C('sqrt(9+7)', r.d === '4', r.d);
await clear(); await tn('4'); await sci('^2'); await eq(); r = await read();
C('4^2', r.d === '16', r.d);
await clear(); await sci('('); await tn('2'); await op('+'); await tn('3'); await sci(')'); await eq(); r = await read();
C('(2+3)', r.d === '5', r.d);
await clear(); await tn('2'); await sci('('); await tn('3'); await op('+'); await tn('4'); await sci(')'); await eq(); r = await read();
C('2(3+4)', r.d === '14', r.d);
await clear(); await tn('2'); await op('+'); await tn('3'); await eq(); r = await read();
C('std 2+3', r.d === '5', r.d);
await clear(); await tn('7'); await op('*'); await tn('8'); await eq(); r = await read();
C('std 7*8', r.d === '56', r.d);
await clear(); await tn('2'); await sci('^'); await tn('3'); await bs(); r = await read();
C('BS 2^3->2', r.d === '2', r.d);
await clear(); await tn('5'); await sci('!'); await bs(); r = await read();
C('BS 5!->5', r.d === '5', r.d);
await clear(); await tn('5'); await sci('!'); await clear(); r = await read();
C('AC->0', r.d === '0', r.d);
await clear(); await tn('2'); await sci('^'); await tn('3'); await eq(); r = await read();
C('hist has 8', /8/.test(r.h), r.h.slice(0, 100));
const langs = ['en', 'ar', 'ku', 'fr', 'de', 'es', 'ru', 'tr'];
for (const L of langs) {
  await page.evaluate((l) => { const s = document.getElementById('topBarLanguageSelect'); s.value = l; s.dispatchEvent(new Event('change', { bubbles: true })); }, L);
  await sleep(200);
  await clear(); await tn('2'); await sci('^'); await tn('3'); await eq(); r = await read();
  C(`lang ${L} 2^3=8`, r.d === '8', r.d);
}
for (const w of [360, 390, 768, 1024, 1280]) {
  await page.setViewport({ width: w, height: 800 }); await sleep(150);
  const inv = await page.evaluate(() => ({ of: document.documentElement.scrollWidth > window.innerWidth + 1, ok: [...document.querySelectorAll('.scientific-btn')].map((b) => { const q = b.getBoundingClientRect(); return q.width >= 40 && q.height >= 40 && q.left >= -1 && q.right <= window.innerWidth + 1; }) }));
  C(`vp ${w}`, inv.of === false && inv.ok.every(Boolean), JSON.stringify(inv));
}
await page.evaluate(() => { const s = document.getElementById('topBarLanguageSelect'); s.value = 'ar'; s.dispatchEvent(new Event('change', { bubbles: true })); });
await sleep(200); r = await read();
C('AR rtl', r.dir === 'rtl', r.dir);
const ne = errs.filter((m) => !/decimal/i.test(m));
C('no new errors', ne.length === 0, ne.slice(0, 2).join('|'));
console.log('FAILS ' + fails);
await browser.close(); server.close();
process.exit(fails ? 1 : 0);
