// PART 5 — SMART DOCUMENTS: Import PDF  (behavioral test in a real Chrome browser)
// Run:  node tests/part5_smart_import.test.mjs
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import puppeteer from 'puppeteer-core';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const CHROME = 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe';
const PORT = 8315;
const MIME = {
  '.html': 'text/html', '.js': 'text/javascript', '.mjs': 'text/javascript',
  '.css': 'text/css', '.json': 'application/json', '.png': 'image/png',
  '.ico': 'image/x-icon', '.svg': 'image/svg+xml', '.jpg': 'image/jpeg',
  '.txt': 'text/plain', '.wasm': 'application/wasm', '.pdf': 'application/pdf'
};
const mimeOf = (p) => MIME[path.extname(p).toLowerCase()] || 'application/octet-stream';

const server = http.createServer((req, res) => {
  let urlPath = decodeURIComponent(req.url.split('?')[0]);
  if (urlPath === '/' || urlPath === '') urlPath = '/index.html';
  const filePath = path.join(ROOT, urlPath);
  try {
    const data = fs.readFileSync(filePath);
    res.writeHead(200, { 'Content-Type': mimeOf(filePath) + '; charset=utf-8' });
    res.end(data);
  } catch (e) {
    res.writeHead(404); res.end('not found');
  }
});
await new Promise((r) => server.listen(PORT, '127.0.0.1', r));
const URL = `http://127.0.0.1:${PORT}/`;
setTimeout(() => process.exit(124), 240000); // hard watchdog

const results = [];
function check(name, ok, detail = '') {
  results.push({ name, ok, detail });
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${detail ? '  -> ' + detail : ''}`);
}

const browser = await puppeteer.launch({
  executablePath: CHROME,
  headless: 'new',
  args: ['--no-sandbox', '--disable-gpu', '--no-first-run', '--disable-dev-shm-usage']
});

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function newPage(viewport) {
  const page = await browser.newPage();
  if (viewport) await page.setViewport(viewport);
  const errs = [];
  page.on('pageerror', (e) => errs.push(String(e && e.message || e)));
  await page.goto(URL, { waitUntil: 'domcontentloaded', timeout: 45000 });
  await sleep(700);
  return { page, errs };
}

async function openDrawer(page) {
  await page.evaluate(() => document.getElementById('drawerToggle').click());
  await sleep(250);
}

async function clickSmartDocs(page) {
  await page.evaluate(() => document.querySelector('.drawer-menu-item[data-action="open-smart-docs"]').click());
  await sleep(400);
}

async function setLang(page, locale) {
  await page.evaluate((l) => {
    const s = document.getElementById('topBarLanguageSelect');
    if (s) { s.value = l; s.dispatchEvent(new Event('change', { bubbles: true })); }
  }, locale);
  await sleep(400);
}

// Upload (or cancel) a file through the system file picker triggered by the Import card.
async function pickFile(page, filePath) {
  const [chooser] = await Promise.all([
    page.waitForFileChooser({ timeout: 9000 }),
    page.evaluate(() => document.querySelector('.smart-doc-card[data-action="smart-import-file"]').click())
  ]);
  if (filePath) await chooser.accept([filePath]);
  else await chooser.cancel();
}

const getState = (page) => page.evaluate(() => (window.__smartImport && window.__smartImport.getState()) || {});
const impStage = async (page) => (await getState(page)).stage;

async function waitFor(page, fn, timeout = 10000) {
  const start = Date.now();
  while (Date.now() - start < timeout) {
    if (await page.evaluate(fn)) return true;
    await sleep(120);
  }
  return false;
}

// Observe the first non-pick stage right after a file is accepted (validates Preparing state).
async function firstStageAfterAccept(page, path) {
  await pickFile(page, path);
  const start = Date.now();
  while (Date.now() - start < 8000) {
    const st = await impStage(page);
    if (st !== 'pick') return st;
    await sleep(60);
  }
  return 'none';
}

// ---------- Fixtures ----------
// Text PDF: real selectable text (generated by Chrome print-to-PDF).
async function makeTextPdf(page) {
  await page.setContent(
    '<html><body style="font-family:Arial"><h1>Quarterly Business Report</h1>' +
    '<p>Revenue increased by twenty percent during the final quarter of this year.</p>' +
    '<p>Expenses remained stable while profit margins improved across all regions.</p>' +
    '<p>We project further growth for the coming fiscal year ahead.</p></body></html>',
    { waitUntil: 'load' }
  );
  await sleep(250);
  await page.pdf({ path: textPdfPath, format: 'A4' });
}
// Scanned PDF: pages contain only vector graphics (no extractable text).
async function makeScannedPdf(page) {
  await page.setContent(
    '<html><body style="margin:0">' +
    '<div style="width:595px;height:842px;background:repeating-linear-gradient(45deg,#cfcfcf,#ffffff 24px)"></div>' +
    '<div style="width:595px;height:842px;background:#999;position:absolute;top:842px;left:0"></div>' +
    '</body></html>',
    { waitUntil: 'load' }
  );
  await sleep(250);
  await page.pdf({ path: scannedPdfPath, format: 'A4' });
}

const textPdfPath = path.join(ROOT, '__part5_text.pdf');
const scannedPdfPath = path.join(ROOT, '__part5_scanned.pdf');
const corruptPdfPath = path.join(ROOT, '__part5_corrupt.pdf');
const invalidPath = path.join(ROOT, '__part5_notpdf.txt');
fs.writeFileSync(corruptPdfPath, 'this is not a valid pdf file, just some random bytes');
fs.writeFileSync(invalidPath, 'just a text file, not a pdf');

try {
  // Build the PDF fixtures using an isolated page in the same browser.
  {
    const p = await browser.newPage();
    await makeTextPdf(p);
    await makeScannedPdf(p);
    await p.close();
  }

  // ================= 1) File Picker: Import card exists + opens the picker =================
  {
    const { page, errs } = await newPage({ width: 1280, height: 800 });
    await openDrawer(page);
    await clickSmartDocs(page);
    const card = await page.evaluate(() => {
      const c = document.querySelector('.smart-doc-card[data-action="smart-import-file"]');
      return c ? { exists: true, title: c.querySelector('.smart-doc-card-title')?.textContent.trim() } : { exists: false, title: null };
    });
    check('File Picker: Import card exists', card.exists);
    check('File Picker: Import card title present', !!(card.title && card.title.length), card.title);
    // Clicking the card opens the system file picker, then we cancel it.
    const [chooser] = await Promise.all([
      page.waitForFileChooser({ timeout: 9000 }),
      page.evaluate(() => document.querySelector('.smart-doc-card[data-action="smart-import-file"]').click())
    ]);
    check('File Picker: clicking Import opens the file picker', !!chooser);
    await chooser.cancel();
    await sleep(400);
    const s = await getState(page);
    check('File Picker: view visible after cancel', s.viewVisible === true);
    check('File Picker: no editor after cancel', s.editorVisible === false);
    check('File Picker: stays on pick stage after cancel', s.stage === 'pick', 'stage=' + s.stage);
    check('File Picker: no JS errors on cancel', errs.length === 0, errs.join(' | '));
    await page.close();
  }

  // ================= 2) Cancel via chooser does not open the editor =================
  {
    const { page, errs } = await newPage({ width: 1280, height: 800 });
    await openDrawer(page);
    await clickSmartDocs(page);
    await pickFile(page, null); // cancel
    await sleep(500);
    const s = await getState(page);
    check('Cancel: no editor opened', s.editorVisible === false, 'editor=' + s.editorVisible);
    check('Cancel: no error shown', s.stage !== 'error', 'stage=' + s.stage);
    check('Cancel: no JS error', errs.length === 0, errs.join(' | '));
    await page.evaluate(() => document.getElementById('smartImportBack').click());
    await sleep(250);
    const homeShown = await page.evaluate(() => document.querySelector('.smart-docs-home')?.style.display !== 'none');
    check('Cancel: back returns to Smart Documents home', homeShown);
    check('Cancel: view hidden after back', (await getState(page)).viewVisible === false);
    await page.close();
  }

  // ================= 3) Text PDF: Preparing state -> Text PDF -> Editor =================
  {
    const { page, errs } = await newPage({ width: 1280, height: 800 });
    await openDrawer(page);
    await clickSmartDocs(page);
    const first = await firstStageAfterAccept(page, textPdfPath);
    check('Text PDF: Preparing state was shown during analysis', first === 'preparing', 'first=' + first);
    const ok = await waitFor(page, () => window.__smartImport.getState().editorVisible === true, 15000);
    const s = await getState(page);
    check('Text PDF: enters editor after successful analysis', ok);
    check('Text PDF: detected as text type', s.type === 'text', 'type=' + s.type);
    check('Text PDF: parsed as text (not scanned)', s.parsedType === 'text', 'parsed=' + s.parsedType);
    check('Text PDF: extracted text length > 0', s.textLen > 0, 'len=' + s.textLen);
    check('Text PDF: workflow step = Edit(2)', s.step === 2, 'step=' + s.step);
    const editorText = await page.evaluate(() => document.getElementById('smartEditorText')?.value || '');
    check('Text PDF: editor holds extracted content', editorText.includes('Quarterly'), editorText.slice(0, 40));
    check('Text PDF: no JS errors', errs.length === 0, errs.join(' | '));
    await page.close();
  }

  // ================= 4) Scanned PDF: detected, message shown, NOT in editor =================
  {
    const { page, errs } = await newPage({ width: 1280, height: 800 });
    await openDrawer(page);
    await clickSmartDocs(page);
    await pickFile(page, scannedPdfPath);
    const ok = await waitFor(page, () => window.__smartImport.getState().stage === 'scanned', 15000);
    const s = await getState(page);
    check('Scanned PDF: detected as scanned', ok && s.parsedType === 'scanned', 'parsed=' + s.parsedType);
    check('Scanned PDF: OCR decision message shown', s.stage === 'scanned', 'stage=' + s.stage);
    check('Scanned PDF: does NOT enter editor before decision', s.editorVisible === false);
    const ui = await page.evaluate(() => ({
      hasOcr: !!document.getElementById('importUseOcrBtn'),
      hasKeep: !!document.getElementById('importKeepImagesBtn'),
      msg: document.getElementById('importStageScanned')?.textContent.trim().slice(0, 60) || ''
    }));
    check('Scanned PDF: Use OCR button present', ui.hasOcr);
    check('Scanned PDF: Keep Pages as Images button present', ui.hasKeep);
    check('Scanned PDF: scanned-title/message text present', ui.msg.length > 0, ui.msg);
    check('Scanned PDF: no JS errors', errs.length === 0, errs.join(' | '));
    await page.close();
  }

  // ================= 5) OCR path: Use OCR -> OCR Processing -> Editor =================
  {
    const { page, errs } = await newPage({ width: 1280, height: 800 });
    await openDrawer(page);
    await clickSmartDocs(page);
    await pickFile(page, scannedPdfPath);
    await waitFor(page, () => window.__smartImport.getState().stage === 'scanned', 15000);
    await page.evaluate(() => window.__smartImport.setOcrText('Recognized line one. Recognized line two.'));
    await page.evaluate(() => document.getElementById('importUseOcrBtn').click());
    const ocrSeen = await waitFor(page, () => window.__smartImport.getState().stage === 'ocr', 4000);
    check('OCR path: OCR Processing stage shown', ocrSeen);
    const ok = await waitFor(page, () => window.__smartImport.getState().editorVisible === true, 12000);
    const s = await getState(page);
    check('OCR path: enters editor after OCR completes', ok);
    check('OCR path: result type is ocr', s.type === 'ocr', 'type=' + s.type);
    check('OCR path: recognized text inserted', s.textLen > 0, 'len=' + s.textLen);
    const editorText = await page.evaluate(() => document.getElementById('smartEditorText')?.value || '');
    check('OCR path: editor holds recognized text', editorText.includes('Recognized'), editorText.slice(0, 40));
    check('OCR path: no JS errors', errs.length === 0, errs.join(' | '));
    await page.close();
  }

  // ================= 6) Image path: Keep Pages as Images -> Editor (no OCR) =================
  {
    const { page, errs } = await newPage({ width: 1280, height: 800 });
    await openDrawer(page);
    await clickSmartDocs(page);
    await page.evaluate(() => window.__smartImport.setOcrText('SHOULD_NOT_BE_USED'));
    await pickFile(page, scannedPdfPath);
    await waitFor(page, () => window.__smartImport.getState().stage === 'scanned', 15000);
    await page.evaluate(() => document.getElementById('importKeepImagesBtn').click());
    const ok = await waitFor(page, () => window.__smartImport.getState().editorVisible === true, 12000);
    const s = await getState(page);
    check('Image path: enters editor', ok);
    check('Image path: result type is images', s.type === 'images', 'type=' + s.type);
    check('Image path: pages inserted as images', s.imageCount >= 1, 'img=' + s.imageCount);
    check('Image path: OCR was NOT run', !s.text || s.text.indexOf('SHOULD_NOT_BE_USED') === -1, 'text=' + (s.text || '').slice(0, 20));
    const imgNodes = await page.evaluate(() => document.querySelectorAll('#smartEditorImages img').length);
    check('Image path: image elements rendered in editor', imgNodes >= 1, 'nodes=' + imgNodes);
    check('Image path: no JS errors', errs.length === 0, errs.join(' | '));
    await page.close();
  }

  // ================= 7) Error: invalid file type =================
  {
    const { page, errs } = await newPage({ width: 1280, height: 800 });
    await openDrawer(page);
    await clickSmartDocs(page);
    await pickFile(page, invalidPath);
    const ok = await waitFor(page, () => window.__smartImport.getState().stage === 'error', 8000);
    const s = await getState(page);
    check('Error: invalid file shows error state', ok, 'stage=' + s.stage);
    check('Error: editor not opened on invalid file', s.editorVisible === false);
    const retryPresent = await page.evaluate(() => !!document.getElementById('importRetryBtn'));
    check('Error: Retry button present', retryPresent);
    check('Error: no JS errors on invalid file', errs.length === 0, errs.join(' | '));
    await page.close();
  }

  // ================= 8) Error: corrupt PDF =================
  {
    const { page, errs } = await newPage({ width: 1280, height: 800 });
    await openDrawer(page);
    await clickSmartDocs(page);
    await pickFile(page, corruptPdfPath);
    const ok = await waitFor(page, () => window.__smartImport.getState().stage === 'error', 10000);
    const s = await getState(page);
    check('Error: corrupt PDF shows error state', ok, 'stage=' + s.stage);
    check('Error: corrupt PDF does not open editor', s.editorVisible === false, 'editor=' + s.editorVisible);
    const errText = await page.evaluate(() => document.getElementById('importErrorText')?.textContent || '');
    check('Error: an in-UI error message is shown', errText.length > 0, errText.slice(0, 40));
    check('Error: no JS errors on corrupt PDF', errs.length === 0, errs.join(' | '));
    await page.close();
  }

  // ================= 9) OCR failure -> error + Retry recovers =================
  {
    const { page, errs } = await newPage({ width: 1280, height: 800 });
    await openDrawer(page);
    await clickSmartDocs(page);
    await pickFile(page, scannedPdfPath);
    await waitFor(page, () => window.__smartImport.getState().stage === 'scanned', 15000);
    await page.evaluate(() => window.__smartImport.setOcrText('')); // empty -> OCR fails
    await page.evaluate(() => document.getElementById('importUseOcrBtn').click());
    const ok = await waitFor(page, () => window.__smartImport.getState().stage === 'error', 10000);
    const s = await getState(page);
    check('OCR failure: error state shown', ok, 'stage=' + s.stage);
    check('OCR failure: editor not opened', s.editorVisible === false);
    check('OCR failure: retry button available', await page.evaluate(() => !!document.getElementById('importRetryBtn')));
    check('OCR failure: no JS errors', errs.length === 0, errs.join(' | '));
    // Retry: choose a valid text PDF -> should recover into the editor.
    const [chooser] = await Promise.all([
      page.waitForFileChooser({ timeout: 9000 }),
      page.evaluate(() => document.getElementById('importRetryBtn').click())
    ]);
    await chooser.accept([textPdfPath]);
    const ok2 = await waitFor(page, () => window.__smartImport.getState().editorVisible === true, 15000);
    const s2 = await getState(page);
    check('Retry: recovers and imports a valid PDF', ok2 && s2.type === 'text', 'type=' + s2.type);
    check('Retry: no JS errors', errs.length === 0, errs.join(' | '));
    await page.close();
  }

  // ================= 10) RTL localization (Arabic) =================
  {
    const { page, errs } = await newPage({ width: 1280, height: 800 });
    await setLang(page, 'ar');
    await openDrawer(page);
    await clickSmartDocs(page);
    await pickFile(page, scannedPdfPath);
    await waitFor(page, () => window.__smartImport.getState().stage === 'scanned', 15000);
    const ui = await page.evaluate(() => ({
      dir: document.documentElement.dir,
      ocrLabel: document.getElementById('importUseOcrBtn')?.textContent.trim(),
      keepLabel: document.getElementById('importKeepImagesBtn')?.textContent.trim(),
      heading: document.getElementById('smartImportTitle')?.textContent.trim()
    }));
    check('RTL: document dir is rtl', ui.dir === 'rtl', ui.dir);
    check('RTL: Use OCR localized (Arabic)', ui.ocrLabel === 'استخدام OCR', ui.ocrLabel);
    check('RTL: Keep Pages as Images localized (Arabic)', ui.keepLabel === 'إبقاء الصفحات كصور', ui.keepLabel);
    check('RTL: import title localized (Arabic)', ui.heading === '📂 استيراد ملف', ui.heading);
    check('RTL: no JS errors', errs.length === 0, errs.join(' | '));
    await page.close();
  }

  // ================= 11) LTR (English) localization =================
  {
    const { page, errs } = await newPage({ width: 1280, height: 800 });
    await setLang(page, 'en'); // reset any persisted locale (e.g. from the Arabic test above)
    await openDrawer(page);
    await clickSmartDocs(page);
    const ui = await page.evaluate(() => ({
      dir: document.documentElement.dir,
      title: document.getElementById('smartImportTitle')?.textContent.trim()
    }));
    check('LTR: document dir is ltr', ui.dir === 'ltr', ui.dir);
    check('LTR: import title localized (English)', ui.title === '📂 Import a File', ui.title);
    check('LTR: no JS errors', errs.length === 0, errs.join(' | '));
    await page.close();
  }

  // ================= 12) Mobile: no horizontal overflow =================
  {
    const { page, errs } = await newPage({ width: 390, height: 844 });
    await openDrawer(page);
    await clickSmartDocs(page);
    await page.evaluate(() => document.querySelector('.smart-doc-card[data-action="smart-import-file"]').click());
    await sleep(400);
    const ov = await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth);
    check('Mobile: no horizontal overflow', ov <= 2, 'overflow=' + ov);
    check('Mobile: no JS errors', errs.length === 0, errs.join(' | '));
    await page.close();
  }

  // ================= 13) Regression: Calculator works =================
  {
    const { page, errs } = await newPage({ width: 1280, height: 800 });
    const r = await page.evaluate(() => {
      const b1 = document.querySelector('.keypad-btn.number[data-value="1"]');
      const b2 = document.querySelector('.keypad-btn.number[data-value="2"]');
      b1.click(); b2.click();
      return document.querySelector('#primaryDisplay').textContent;
    });
    check('Regression: Calculator still works (1 then 2 = 12)', r === '12', 'display=' + r);
    check('Regression: no JS errors (calculator)', errs.length === 0, errs.join(' | '));
    await page.close();
  }

  // ================= 14) Regression: History + Notes drawer items =================
  {
    const { page, errs } = await newPage({ width: 1280, height: 800 });
    await openDrawer(page);
    const items = await page.evaluate(() => ({
      history: !!document.querySelector('.drawer-menu-item[data-action="open-history"]'),
      notes: !!document.querySelector('.drawer-menu-item[data-action="open-notes"]'),
      smartDocs: !!document.querySelector('.drawer-menu-item[data-action="open-smart-docs"]')
    }));
    check('Regression: History entry intact', items.history);
    check('Regression: Notes entry intact', items.notes);
    check('Regression: Smart Documents entry intact', items.smartDocs);
    check('Regression: no JS errors (drawer)', errs.length === 0, errs.join(' | '));
    await page.close();
  }

  // ================= 15) Regression: Smart Docs PART 1-3 + PART 4 scan unaffected =================
  {
    const { page, errs } = await newPage({ width: 1280, height: 800 });
    await openDrawer(page);
    await clickSmartDocs(page);
    const home = await page.evaluate(() => ({
      shown: document.getElementById('smartDocsModal').classList.contains('show'),
      cards: document.querySelectorAll('.smart-doc-card').length,
      steps: document.querySelectorAll('[data-widget="smart-steps"] .smart-step').length
    }));
    check('Regression: Smart Docs opens (P1)', home.shown);
    check('Regression: four cards intact (P2)', home.cards === 4, 'cards=' + home.cards);
    check('Regression: four workflow steps intact (P3)', home.steps === 4, 'steps=' + home.steps);
    await page.evaluate(() => document.querySelector('.smart-doc-card[data-action="smart-scan-doc"]').click());
    await sleep(600);
    const scanVisible = await page.evaluate(() => document.getElementById('smartScanView').classList.contains('scan-visible'));
    check('Regression: PART 4 scan workflow still opens', scanVisible);
    check('Regression: no JS errors', errs.length === 0, errs.join(' | '));
    await page.close();
  }

} catch (err) {
  console.log('ERROR', err);
  results.push({ name: 'test harness', ok: false, detail: String(err && err.stack || err) });
} finally {
  try { await browser.close(); } catch (e) {}
  try { fs.unlinkSync(textPdfPath); } catch (e) {}
  try { fs.unlinkSync(scannedPdfPath); } catch (e) {}
  try { fs.unlinkSync(corruptPdfPath); } catch (e) {}
  try { fs.unlinkSync(invalidPath); } catch (e) {}
  server.close();
}

const failed = results.filter((r) => !r.ok);
console.log(`\n${failed.length === 0 ? 'ALL PASS' : failed.length + ' FAILED'}  (${results.length} checks)`);
process.exit(failed.length === 0 ? 0 : 1);
