import fs from 'node:fs';
const a = fs.readFileSync('app.js', 'utf8');
const h = fs.readFileSync('index.html', 'utf8');
const c = fs.readFileSync('styles.css', 'utf8');
let fail = 0;
const chk = (n, ok, d='') => { console.log((ok?'PASS':'FAIL')+'  '+n+(d?'  -> '+d:'')); if(!ok) fail++; };
chk('featureNav circled btn keeps data-action open-smart-docs', h.includes('feature-nav-btn" data-action="open-smart-docs"'));
chk('featureNav intercept routes to openPdfReportsWorkspace', a.includes("btn.closest('#featureNavBar')") && a.includes('openPdfReportsWorkspace()'));
chk('drawer open-smart-docs still opens Smart Docs', a.includes("case 'open-smart-docs':") && h.includes('drawer-menu-item" data-action="open-smart-docs"'));
chk('smartDocsModal untouched', h.includes('id="smartDocsModal"') && a.includes('function openSmartDocs()'));
chk('no new workspace created', ((a.match(/function openPdfReportsWorkspace/g)||[]).length===1) && h.includes('id="pdfReportsWorkspace"') && !h.includes('pdfV1Workspace'));
chk('Phase1 ids present inside pdfReportsWorkspace', ['pdfV1FileInput','pdfV1Dropzone','pdfV1BrowseBtn','pdfV1Error','pdfV1ViewerWrap','pdfV1Viewer','pdfV1FileName','pdfV1ChangeBtn'].every(id=>h.includes('id="'+id+'"')));
chk('Phase1 nested in pdfReportsWorkspace', h.indexOf('id="pdfV1Dropzone"') > h.indexOf('id="pdfReportsWorkspace"'));
chk('file input PDF only', h.includes('accept="application/pdf,.pdf"'));
chk('viewer is native iframe + blob', a.includes('URL.createObjectURL(file)') && h.includes('<iframe id="pdfV1Viewer"'));
chk('cancel handled', a.includes('if (!file) return;'));
chk('non-PDF rejected', a.includes('pdfV1IsPdfFile') && a.includes('That file is not a PDF'));
chk('drop handler present', a.includes("addEventListener('drop'") && a.includes('dataTransfer'));
chk('revoke old URL', a.includes('URL.revokeObjectURL'));
chk('wired in wireEvents', a.includes('pdfV1WireImport();'));
chk('css scoped to #pdfReportsWorkspace', c.includes('#pdfReportsWorkspace .pdfv1-dropzone') && c.includes('#pdfReportsWorkspace .pdfv1-viewer'));
const segSrc = a.slice(a.indexOf('let pdfV1ObjectUrl'), a.indexOf('function openSmartDocs'));
const seg = segSrc.toLowerCase();
chk('no Phase2 in pdfV1 segment', !/export|print|share|whatsapp|telegram|email|stamp|signature|overlay|merge|split|compress|conver|server|cloud/.test(seg));
console.log(fail===0 ? 'STATIC ALL PASS' : 'STATIC FAILURES: '+fail);
process.exit(fail===0?0:1);
