// Kurdish Sorani (ku) translation dataset — natural, production-grade Central Kurdish.
export const ku = {
  "eyebrow": "",
  "title": "EQ7",
  "install": "دامەزراندنی بەرنامە",
  "actions": "کردارەکان",
  "notesManagerTitle": "بەڕێوەبەری تێبینییەکان",
  "notesManagerSubtitle": "تێبینییەکان لەناو فۆڵدەرەکاندا ڕێکبخە و سەرنووسەری تەواوی شاشە بکەرەوە.",
  "foldersTitle": "فۆڵدەرەکان",
  "addFolder": "+ فۆڵدەر",
  "newNoteButton": "تێبینی نوێی تەواوی شاشە",
  "notesTitle": "تێبینییەکان",
  "refreshNotes": "نوێکردنەوە",
  "fullScreenNoteTitle": "تێبینی تەواوی شاشە",
  "noteFolderLabel": "فۆڵدەر",
  "noteTitleLabel": "ناونیشان",
  "noteTitlePlaceholder": "ناونیشانی تێبینی",
  "folderSelectLabel": "فۆڵدەر",
  "noteBodyPlaceholder": "دەست بە نووسین بکە...",
  "noteTableInsertPopupTitle": "زیادکردنی خشتە",
  "noteHeadingMenuLabel": "سەرنووسە",
  "noteHeading1Label": "سەرنووسەی 1",
  "noteHeading2Label": "سەرنووسەی 2",
  "noteHeading3Label": "سەرنووسەی 3",
  "noteNormalTextLabel": "دەقی ئاسایی",
  "noteTableRowsLabel": "ڕیزەکان",
  "noteTableColsLabel": "ستوونەکان",
  "noteTableHeaderRowLabel": "ڕیزی سەرەکی",
  "noteTableInsertBtnLabel": "زیادکردنی خشتە",
  "noteImageLabel": "وێنە",
  "noteImageUpload": "بارکردن",
  "noteImageCamera": "کامێرا",
  "noteTablePresetCustomLabel": "تایبەت",
  "untitled": "بێ ناونیشان",
  "pdfPreviewTitle": "پێشبینینی PDF",
  "pdfPrevPage": "پەڕەی پێشوو",
  "pdfNextPage": "پەڕەی دواتر",
  "pdfZoomIn": "گەورەکردنەوە",
  "pdfZoomOut": "بچووککردنەوە",
  "pdfZoomFit": "گونجاندنی پەڕە",
  "pdfRotate": "سووڕاندنەوە",
  "pdfShare": "هاوبەشکردن / پاشەکەوتکردنی PDF",
  "pdfClose": "داخستنی پێشبینین",
  "pdfMore": "ئامرازە زیاترەکان",
  "pdfPrint": "چاپکردن",
  "pdfSave": "پاشەکەوتکردن لە ئامێرەکە",
  "pdfAnnoEdit": "دەستکاری لێدوانەکان",
  "pdfAnnoText": "زیادکردنی دەق",
  "pdfAnnoHighlight": "بەرچاوکردن",
  "pdfAnnoDraw": "وێنەکێشان",
  "pdfAnnoUnderline": "ژێرهێڵکردن",
  "pdfAnnoStrike": "هێڵکاری سەر",
  "pdfAnnoRect": "لاکێشە",
  "pdfAnnoCircle": "بازنە",
  "pdfAnnoLine": "هێڵ",
  "pdfAnnoClear": "سڕینەوەی لێدوانەکانی پەڕە",
  "pdfAnnoNote": "زیادکردنی تێبینی",
  "pdfDocOptions": "هەڵبژاردەکانی بەڵگە",
  "pdfDocTemplate": "قاڵب",
  "pdfDocHeader": "سەرپەڕە",
  "pdfDocFooter": "ژێرپەڕە",
  "pdfDocWatermark": "نیشانی ئاوی",
  "pdfDocWmText": "دەقی نیشانی ئاوی",
  "pdfTplBlank": "بەتاڵ",
  "pdfTplReport": "ڕاپۆرت",
  "pdfTplInvoice": "فاکتوور",
  "pdfTplReceipt": "وەسڵ",
  "pdfTplContract": "پەیماننامە",
  "pdfTplCv": "سیڤی",
  "pdfTplBusiness": "ڕاپۆرتی بازرگانی",
  "pdfTplEngineering": "ڕاپۆرتی ئەندازیاری",
  "pdfTplLetter": "نامە",
  "folderPersonal": "تایبەت",
  "percentTab": "سەدا",
  "settingsTab": "ڕێکخستنەکان",
  "historyTab": "مێژوو",
  "percentTitle": "حیسابکەری سەدا",
  "percentBack": "گەڕانەوە",
  "amountLabel": "بڕ",
  "rateLabel": "ڕێژەی سەدا",
  "settingsTitle": "ڕێکخستن و تایبەتمەندی",
  "languageLabel": "زمان",
  "themeLabel": "ڕوانگە",
  "historyTitle": "مێژووی 24 کاتژمێر",
  "historyBack": "گەڕانەوە",
  "historyRemaining": "ماوە",
  "selectAll": "هەڵبژاردنی هەموو",
  "exportButton": "هاوبەشکردن / دەرهێنان",
  "companyNameBtn": "ناوی کۆمپانیا",
  "quickNotesTitle": "تێبینی خێرا",
  "quickNotesToggle": "▼",
  "quickNotesAdd": "پاشەکەوتکردن",
  "quickNotesPlaceholder": "تێبینی بنووسە",
  "historyNotePlaceholder": "نیشانەکردنی ئەم حیسابە",
  "historyInsertResult": "زیادکردنی ئەنجام",
  "historySpeakResult": "خوێندنەوەی ئەنجام بە دەنگ",
  "historyLabel": "مێژوو",
  "noteLabel": "تێبینی",
  "noteInputPlaceholder": "+ تێبینی نوێ",
  "noteSaved": "تێبینی پاشەکەوتکرا",
  "noteEdit": "دەستکاری",
  "noteShare": "هاوبەشکردن",
  "emptyHistory": "هێشتا مێژوو نییە",
  "noteTableAddRow": "+ ڕیز",
  "noteTableAddCol": "+ ستوون",
  "noteTableDelRow": "- ڕیز",
  "noteTableDelCol": "- ستوون",
  "noteTableMergeCells": "تێکەڵکردنی خانەکان",
  "noteTableSplitCell": "دابەشکردنی خانە",
  "copied": "ئەنجام هەڵگیرا",
  "pasted": "ژمارە لێنرا",
  "installed": "بەرنامە ئامادەیە بۆ دامەزراندن",
  "noSelection": "شتێک هەڵبژێرە بۆ هاوبەشکردن",
  "shareTitle": "مێژووی حیسابکەری EQ7",
  "shareMessage": "لە حیسابکەری EQ7 دەرهێنراوە",
  "themeDark": "تور",
  "themeLight": "ڕووناک",
  "themeViolet": "بەنەفش",
  "languageEnglish": "English",
  "noteTableBorderAll": "هەموو سنوورەکان",
  "noteTableBorderOutside": "سنوورە دەرەکییەکان",
  "noteTableBorderInside": "سنوورە ناوەکییەکان",
  "noteTableBorderNone": "بێ سنوور",
  "noteTableHAlignLeft": "چەپ",
  "noteTableHAlignCenter": "ناوەڕاست",
  "noteTableHAlignRight": "ڕاست",
  "noteTableVAlignTop": "سەرەوە",
  "noteTableVAlignMiddle": "ناوەڕاست",
  "noteTableVAlignBottom": "خوارەوە",
  "languageSpanish": "Español",
  "languageArabic": "العربية",
  "languageFrench": "Français",
  "languageRussian": "Русский",
  "languageGerman": "Deutsch",
  "languageTurkish": "Türkçe",
  "languageKurdish": "کوردی",
  "drawerTop": "سەرەوە",
  "drawerSide": "لەلایەوە",
  "expand": "کردنەوە",
  "Minimize": "بچووککردنەوە",
  "installModalSubtitle": "زیادی بکە بۆ شاشەی سەرەکی",
  "installModalClose": "تێگەیشتم",
  "settingsSubtitle": "زمان، ڕوانگە و کاردانەوەی بەرنامەکە ڕێکبخە.",
  "appSoundsLabel": "دەنگەکانی بەرنامە",
  "soundHapticsLabel": "دەنگی دوگمە و هەست",
  "soundHapticsCaption": "چالاککردنی دەنگی کلیک و لەرینەوە",
  "soundProfileLabel": "پرۆفایلی دەنگی دوگمە",
  "profileClassic": "کلاسیک",
  "profileSoft": "نەرم",
  "profileModern": "مۆدێرن",
  "profileClick": "کلیک",
  "profileSilent": "بێدەنگ",
  "speakerLabel": "قسەکەر / خوێندنەوە بە دەنگ",
  "speakerCaption": "کاتێک چالاکە، ئەنجامەکە دوای پەنجەدان بە = بە شێوەیەکی خۆکار خوێنراوە. کاتێک ناچالاکە، خوێندنەوەکە تەنها لە ڕێگەی دوگمەی قسەکەرەوە دەکرێت.",
  "modeGeneral": "حیسابکەری گشتی",
  "scientificToggle": "زانستی",
  "percentResultLabel": "ئەنجام",
  "currencyConverterTitle": "گۆڕینی دراو",
  "currencyConverterSubtitle": "بڕەکان بە شێوەیەکی خێرا بە نرخی ڕاستەوخۆ بگۆڕە.",
  "resetButton": "بەگەڕخستنەوە",
  "swapButton": "ئاڵوگۆڕ",
  "favoritesButton": "دڵخوازەکان",
  "recentButton": "نوێترین",
  "fromLabel": "لە",
  "toLabel": "بۆ",
  "convertedLabel": "گۆڕدراو",
  "bankRateMode": "🏦 نرخی بانک",
  "marketRateMode": "🏪 نرخی بازار",
  "marketRateFieldLabel": "نرخی ئاڵوگۆڕی بازار",
  "cachedLabel": "پاشەکەوتکراو",
  "refreshButton": "نوێکردنەوە",
  "globalDirectoryButton": "فەهرەستی جیهانی",
  "currencyDirectoryTitle": "فەهرەستی جیهانی دراوەکان",
  "currencyDirectorySubtitle": "دراوە کاغەزییەکان بە ناوی وڵات یان کۆدی دراو بگەڕە.",
  "currencySearchPlaceholder": "گەڕان بە وڵات یان کۆد",
  "drawerEyebrow": "",
  "drawerTitle": "EQ7",
  "drawerHistory": "مێژوو",
  "drawerNotes": "تێبینییەکان",
  "drawerPdf": "PDF",
  "pdfWorkspaceTitle": "PDF",
  "pdfCardScanTitle": "سکانکردن / دروستکردنی PDF",
  "pdfCardScanDesc": "لە بەڵگەکانەوە PDF دروست بکە",
  "pdfCardOpenTitle": "کردنەوەی PDF",
  "pdfCardOpenDesc": "دەستکاری PDF ی هەبوو",
  "pdfRecentTitle": "PDF ی نوێ",
  "pdfRecentEmpty": "هێشتا PDF ی نوێ نییە.",
  "pdfComingSoon": "لە نوێکردنەوەی داهاتوودا دێت.",
  "smartDocsTitle": "📄 بەڵگە ژیرەکان",
  "smartDocsDesc": "بەڵگەکانت لە پەڕەیەکی سەرەکییەوە بەڕێوەببە. ئامرازە نوێیەکان لێرە دەردەکەون.",
  "smartDocsHeading": "دەتەوێت چی بکەیت؟",
  "smartDocsStep1": "دەستپێکردن",
  "smartDocsStep2": "دەستکاری",
  "smartDocsStep3": "پێداچوونەوە",
  "smartDocsStep4": "دەرهێنان",
  "smartDocsCardScanTitle": "سکانکردنی بەڵگەیەک",
  "smartDocsCardScanDesc": "وێنەی کاغەزێک یان پەیماننامەیەک بگرە و بیکە بە ناوەڕۆکی دەستکاریکراو.",
  "smartDocsCardImportTitle": "هاواردنی فایل",
  "smartDocsCardImportDesc": "PDF یەک یان فایلێکی پشتگیریکراو لە ئامێرەکەت هەڵبژێرە.",
  "smartDocsCardNewTitle": "بەڵگەی نوێ",
  "smartDocsCardNewDesc": "پەڕەیەکی بەتاڵ بۆ دەستپێکردن لە سفرەوە.",
  "smartDocsCardTemplatesTitle": "قاڵبەکان",
  "smartDocsCardTemplatesDesc": "قاڵبی ئامادە بۆ دەستپێکردنی خێرا.",
  "smartTemplatesBusiness": "بازرگانی",
  "smartTemplatesPersonal": "تایبەت",
  "smartTemplatesCustom": "تایبەت",
  "smartTemplatesInvoice": "فاکتوور",
  "smartTemplatesQuote": "نرخنامە",
  "smartTemplatesPaymentAgreement": "ڕێکەوتنامەی پارەدان",
  "smartTemplatesServiceContract": "پەیماننامەی ڕاژە",
  "smartScanTitle": "📸 سکانکردنی بەڵگە",  "smartScanEditHint": "دەتوانیت دەقی ناسینراو دەستکاری بکەیت پێش وەرگرتن.",
  "smartScanRescan": "سکانکردنەوە",
  "smartScanAccept": "وەرگرتنی ئەنجام",
  "smartScanStructTitle": "ساختە دۆزراوەکان",
  "smartScanReviewNote": "بەڵگە ناسینرا. دەقی ناوەڕۆکە بپێداچووە پێش دروستکردنی PDF.",
  "smartScanStatusNeeds": "پێویستی پێداچوونەوەیە",
  "smartScanStatusEdited": "دەستکاریکراو — ڕاستکردنەکانت لە PDF دا بەکاردەبرێن",
  "smartScanStructHeading": "سەرنووسە",
  "smartScanStructParagraph": "بەش",
  "smartScanStructTable": "خشتە",
  "smartScanStructNumber": "ژمارە",
  "smartScanStructDate": "بەروار",
  "smartScanStructField": "هەڵگە",
  "smartScanCameraUnavailable": "کامێرا لەسەر ئەم ئامێرە بەردەست نییە.",
  "smartScanPermissionDenied": "ڕێگا بە کامێراکە نەدرا.",
  "smartScanNoText": "هیچ دەق دۆز نەکراو. دووبارە هەوڵ بکە یان وێنەیەک زیاد بکە.",
  "smartScanOcrFailed": "خوێندنەوەی دەق شکستی خوارد. تکایە دووبارە هەوڵ بکەرەوە.",
  "smartScanAccepted": "ئەنجام وەرگیرا و ئامادەیە بۆ دەستکاری.",
  "smartScanEditTitle": "بەڵگەی دەستکاریکراو",
  "smartScanEditDocTitlePh": "ناونیشانی بەڵگە",
  "smartScanCreatePdf": "دروستکردنی PDF",
  "smartScanPdfCreating": "دروستکردنی PDF...",
  "smartScanPdfCreated": "PDF لە بەڵگەی دەستکاریکراوەوە دروستکرا.",
  "smartScanOfflinePdf": "ناتۆراو — کتێبخانەی PDF نەتوانرا باربکرێت.",
  "smartScanPdfFailed": "نەتوانرا PDF دروست بکەین.",
  "smartImportTitle": "📂 هاواردنی فایل",
  "pdfAddTitle": "زیادکردن بۆ PDF",
  "pdfAddText": "دەق",
  "pdfAddImage": "وێنە",
  "pdfAddLogo": "لۆگۆ",
  "pdfAddSignature": "واژۆ",
  "pdfAddStamp": "مۆر",
  "pdfAddDate": "بەروار",
  "pdfAddTable": "خشتە",
  "smartImportPickPrompt": "فایلی PDF یەک لە ئامێرەکەت هەڵبژێرە.",
  "smartImportChoose": "هەڵبژاردنی فایل",
  "smartImportPreparing": "ئامادەکردنی بەڵگە...",
  "smartImportAnalyzing": "شیکردنەوەی بەڵگەکە...",
  "smartImportScannedTitle": "بەڵگەی سکانکراو دۆزکرا",
  "smartImportScannedMsg": "واکوایە ئەم بەڵگە پەڕەی سکانکراوی لەخۆیەتی. دەتەوێت بە ناسینەوەی دەق بەکارببەیت؟",
  "smartImportUseOcr": "بەکارهێنانی ناسینەوە",
  "smartImportKeepImages": "پاشەکەوتکردنی پەڕەکان وەک وێنە",
  "smartImportOcrProcessing": "ناوەڕۆکی ناسینەوە...",
  "smartImportFailed": "شکستی لە هاواردن",
  "smartImportRetry": "دووبارە هەوڵکردنەوە",
  "smartImportInvalidFile": "ئەم فایلە PDF ی ڕەوای نییە. تکایە فایلی PDF هەڵبژێرە.",
  "smartImportCorrupt": "واکوایە PDF یەکە بەرایشێکی هەیە یان نەتوانرا بخوێنرێت. تکایە فایلێکی تر هەڵبژێرە.",
  "smartImportEmpty": "ئەم بەڵگە هیچ ناوەڕۆکی بەکارهێنراوی نییە.",
  "smartImportOcrFailed": "ناسینەوەی دەق شکستی خوارد. تکایە دووبارە هەوڵ بکەرەوە.",
  "smartEditorTitle": "دەستکاریکەر",
  "smartEditorHint": "ناوەڕۆکی بەڵگە",
  "smartEditorPlaceholder": "ناوەڕۆکی هاواردکراو لێرە دەردەکەوێت...",
  "smartToolbarDefault": "بەڵگەی نوێ",
  "smartToolbarUndo": "گەڕانەوە",
  "smartToolbarRedo": "دووبارەکردنەوە",
  "smartToolbarBold": "قەڵەو",
  "smartToolbarItalic": "لاری",
  "smartToolbarUnderline": "ژێرهێڵ",
  "smartDocumentBackLabel": "بەڵگە ژیرەکان",
  "smartToolbarAdd": "زیادکردن",
  "smartAddHeading": "سەرنووسە",
  "smartAddNewPage": "پەڕەی نوێ",
  "smartPageDesignNone": "بێ سنوور",
  "smartPageDesignSimple": "ئاسان",
  "smartPageDesignClassic": "کلاسیک",
  "smartPageDesignFormal": "فەرمی",
  "smartPageDesignModern": "مۆدێرن",
  "smartSigDraw": "وێنەکێشان",
  "smartSigType": "نووسین",
  "smartSigImage": "وێنە",
  "smartSigInsert": "زیادکردن",
  "smartSigClear": "سڕینەوە",
  "smartSigCancel": "هەڵوەشاندنەوە",
  "smartSigNamePh": "ناوت",
  "smartSigChoose": "وێنەی واژۆکەت هەڵبژێرە",
  "smartSigStatusSigned": "✓ واژۆکراو",
  "smartSigStatusModified": "⚠ بەڵگەکە دوای واژۆکردن گۆڕدراوە",
  "smartSigResign": "دووبارە واژۆکردنەوە",
  "smartTextFont": "فۆنت",
  "smartTextSize": "قەبارە",
  "smartTextFontDefault": "بنەمایی",
  "smartTextBold": "قەڵەو",
  "smartTextItalic": "لاری",
  "smartTextUnderline": "ژێرهێڵ",
  "smartTextAlignLeft": "ڕێکخستن بۆ چەپ",
  "smartTextAlignCenter": "ناوەڕاست",
  "smartTextAlignRight": "ڕێکخستن بۆ ڕاست",
  "smartTextDirection": "ئاڕاستەکردن",
  "smartTextDirAuto": "خۆکار",
  "smartTextDirLtr": "LTR",
  "smartTextDirRtl": "RTL",
  "smartTextSpacing": "بۆشایی ڕیزەکان",
  "smartToolbarText": "دەق",
  "smartToolbarTable": "خشتە",
  "smartTableRows": "ڕیزەکان",
  "smartTableColumns": "ستوونەکان",
  "smartTableCreate": "دروستکردنی خشتە",
  "smartTableAddRow": "زیادکردنی ڕیز",
  "smartTableDelRow": "سڕینەوەی ڕیز",
  "smartTableAddCol": "زیادکردنی ستوون",
  "smartTableDelCol": "سڕینەوەی ستوون",
  "smartTableAlignLeft": "ڕێکخستن بۆ چەپ",
  "smartTableAlignCenter": "ناوەڕاست",
  "smartTableAlignRight": "ڕێکخستن بۆ ڕاست",
  "smartToolbarSignature": "واژۆ",
  "smartToolbarMore": "زیاتر",
  "smartToolbarImage": "وێنە",
  "smartImageDelete": "سڕینەوەی وێنە",
  "smartToolbarLogo": "لۆگۆ",
  "smartLogoPosition": "شوێنی لۆگۆ",
  "smartLogoTopRight": "لەسەر بۆ ڕاست",
  "smartLogoTopLeft": "لەسەر بۆ چەپ",
  "smartLogoCenter": "ناوەڕاست",
  "smartToolbarDivider": "جیاکەرەوە",
  "smartToolbarBorder": "سنوور",
  "smartToolbarPage": "پەڕە",
  "smartToolbarPageNumber": "ژمارەی پەڕە",
  "smartToolbarPageSettings": "ڕێکخستنەکانی پەڕە",
  "smartBlankNavPage": "پەڕە",
  "smartBlankNavPrev": "پێشوو",
  "smartBlankNavNext": "دواتر",
  "smartPageAdd": "زیادکردنی پەڕە",
  "smartPageCopy": "کۆپیکردنی پەڕە",
  "smartPageDelete": "سڕینەوەی پەڕە",
  "smartToolbarSave": "پاشەکەوتکردن",
  "smartSavedToast": "بەڵگە پاشەکەوتکرا",
  "smartPdfTextColor": "ڕەنگی دەق",
  "smartPdfStyle": "شێواز",
  "smartPdfStyleNone": "بێ شێواز",
  "smartPdfStyleSimple": "ئاسان",
  "smartPdfStyleBusiness": "بازرگانی",
  "smartPdfStyleAcademic": "ئەکادیمی",
  "smartPdfStyleEngineering": "ئەندازیاری",
  "smartPdfAdd": "زیادکردن",
  "smartPdfAddText": "دەق",
  "smartPdfAddImage": "وێنە",
  "smartPdfAddLogo": "لۆگۆ",
  "smartPdfAddSignature": "واژۆ",
  "smartPdfAddStamp": "مۆر",
  "smartPdfAddDate": "بەروار",
  "smartPdfAddTable": "خشتە",
  "smartPdfMark": "نیشانەکردن",
  "smartPdfMarkHighlight": "بەرچاوکردن",
  "smartPdfMarkUnderline": "ژێرهێڵکردن",
  "smartPdfMarkDraw": "وێنەکێشان",
  "smartPdfMarkComment": "لێدوان",
  "smartPdfMarkDone": "تەواو",
  "smartPdfMarkCancel": "هەڵوەشاندنەوە",
  "smartPdfCommentTitle": "لێدوان",
  "smartPdfCommentText": "دەقی لێدوان",
  "smartPdfCommentAdd": "زیادکردنی لێدوان",
  "smartPdfMarkSelectText": "پێشوو دەقەکە هەڵبژێرە بۆ نیشانەکردن",
  "smartPdfMarkDrawHint": "لەسەر پەڕەکە وێنە بکێشە",
  "smartPdfMarkCommentLabel": "دەقی لێدوان",
  "smartPdfMarkAddComment": "زیادکردنی لێدوان",
  "pdfTblRow": "زیادکردنی ڕیز",
  "pdfTblRowDel": "سڕینەوەی ڕیز",
  "pdfTblCol": "زیادکردنی ستوون",
  "pdfTblColDel": "سڕینەوەی ستوون",
  "pdfTblAlignL": "چەپ",
  "pdfTblAlignC": "ناوەڕاست",
  "pdfTblAlignR": "ڕاست",
  "pdfTblBold": "قەڵەو",
  "pdfTblItalic": "لاری",
  "pdfTblTextColor": "ڕەنگی دەق",
  "pdfTblBg": "پاشینەوان",
  "pdfTblBorder": "ڕەنگی سنوور",
  "pdfTblNoBorder": "بێ سنوور",
  "pdfTblRowH": "بەرزی ڕیز",
  "pdfTblControls": "کۆنترۆڵەکانی خشتە",
  "smartPdfPages": "پەڕەکان",
  "pdfPgAdd": "زیادکردنی پەڕە",
  "pdfPgDel": "سڕینەوەی پەڕە",
  "pdfPgRot": "سووڕاندنەوە",
  "pdfPgDup": "کۆپیکردن",
  "pdfPgAdded": "پەڕە زیادکرا",
  "pdfPgDeleted": "پەڕە سڕایەوە",
  "pdfPgRotated": "سووڕاندراوە",
  "pdfPgDuplicated": "پەڕە کۆپیکرا",
  "pdfPgLast": "بەڵگە دەبێت بەلایەنی کەم لە یەک پەڕەی تێبکەی",
  "smartSaveFailed": "نەتوانرا پاشەکەوتبکەین. تکایە دووبارە هەوڵ بکەرەوە.",
  "smartUnsavedTitle": "دەتەوێت گۆڕانکارییەکانت پاشەکەوتبکەیت پێش دەرچوون؟",
  "smartReviewButton": "پێداچوونەوە",
  "smartReviewExit": "گەڕانەوە بۆ دەستکاری",
  "smartPdfExportButton": "دەرهێنانی PDF",
  "smartPdfExportTitle": "دەرهێنانی PDF",
  "smartPdfExportFilenameLabel": "ناوی فایل",
  "smartPdfExportPagesLabel": "پەڕەکان",
  "smartPdfExportAllPages": "هەموو پەڕەکان",
  "smartPdfExportCurrentPage": "پەڕەی ئێستا",
  "smartPdfExportQualityLabel": "کوالیتی",
  "smartPdfExportNormal": "ئاسایی",
  "smartPdfExportHigh": "بەرز",
  "smartPdfExportDo": "دەرهێنان",
  "smartPdfExportCancel": "هەڵوەشاندنەوە",
  "smartPdfExportSuccess": "PDF بە سەرکەوتووی دەرهێنرا.",
  "smartPdfExportFailed": "دروستکردنی PDF شکستی خوارد.",
  "smartPdfPreparing": "ئامادەکردنی بەڵگە...",
  "smartPdfPrepareFailed": "نەتوانرا PDF ئامادە بکەین. تکایە دووبارە هەوڵ بکەرەوە.",
  "smartPdfResultTitle": "بەڵگە بە سەرکەوتووی دروستکرا",
  "smartPdfResultFileLabel": "فایل",
  "smartPdfOpen": "کردنەوەی PDF",
  "smartPdfShare": "هاوبەشکردن",
  "smartPdfSend": "ناردن",
  "smartPdfClose": "داخستن",
  "smartPdfShareUnsupported": "هاوبەشکردنی ڕاستەوخۆ لەسەر ئەم ئامێرە پشتگیر نییە. PDF یەکە دابەزیرکرا.",
  "smartPdfShareCancelled": "هاوبەشکردن هەڵوەشایەوە.",
  "smartPdfShareFailed": "هاوبەشکردن شکستی خوارد. PDF یەکە دابەزیرکرا.",
  "smartPdfOpenFailed": "نەتوانرا PDF یەکە لەم براوسەرەدا بکەینەوە.",
  "smartPdfPreviewTitle": "پێشبینین",
  "smartPdfPreviewNote": "ئەمە ئەو فایلەیە کە دەپاشەکەوتکرێت.",
  "smartUnsavedSave": "پاشەکەوتکردن",
  "smartUnsavedExit": "دەرچوون بەبێ پاشەکەوتکردن",
  "smartUnsavedCancel": "هەڵوەشاندنەوە",
  "smartUnsavedNewTitle": "گۆڕانکارییە پاشەکەوتنەکراوەکانت هەیە.",
  "smartUnsavedSaveContinue": "پاشەکەوتکردن و بەردەوامبوون",
  "smartUnsavedStartNew": "دەستپێکردنی بەڵگەی نوێ",
  "smartSaveAndContinueFailed": "پاشەکەوتکردن شکستی خوارد. گۆڕانکارییەکانت لەدەست نەچوون.",
  "smartDraftBannerTitle": "پێشنووس لەسەر ئەم ئامێرە پاشەکەوتکرا",
  "smartDraftResume": "بەردەوامبوون لە پێشنووس",
  "smartDraftsTitle": "پێشنووسەکانت",
  "smartDraftsEmpty": "هێشتا هیچ پێشنووسێک پاشەکەوت نەکراوە",
  "smartDraftsNewDoc": "بەڵگەی بەتاڵ",
  "smartDraftResumeBtn": "بەردەوامبوون لە دەستکاری",
  "smartDraftDeleteBtn": "سڕینەوە",
  "smartDraftDelTitle": "ئەم پێشنووسە بسڕەوە؟",
  "smartDraftDelConfirm": "سڕینەوە",
  "smartRelNow": "ئێستا",
  "smartRelMin": "خولەکێک پێش ئێستا",
  "smartRelMins": "{n} خولەک پێش ئێستا",
  "smartRelHour": "کاتژمێرێک پێش ئێستا",
  "smartRelHours": "{n} کاتژمێر پێش ئێستا",
  "smartRelYesterday": "دوێنێ",
  "smartRelDays": "{n} ڕۆژ پێش ئێستا",
  "drawerConverter": "گۆڕەری ڕاستەوخۆی دراو",
  "drawerDirectory": "فەهرەست و گەڕانی جیهانی دراو",
  "drawerInstall": "دامەزراندنی بەرنامە",
  "drawerSettings": "ڕێکخستنەکان",
  "installModalTitle": "دامەزراندن لە ئایفۆن",
  "installModalStep1": "هەنگاوی 1: دوگمەی هاوبەشکردن (⎘ / ⇡) لە بن یان سەری براوسەرەکە دابگرە.",
  "installModalStep2": "هەنگاوی 2: لە لێستەکە \"زیادکردن بۆ شاشەی سەرەکی\" هەڵبژێرە.",
  "currencyOptionSearch": "گەڕانی دراو",
  "currencyOptionPrices": "نرخە ڕاستەوخۆییەکان",
  "featureRequiresInternet": "ئەم تایبەتمەندییە پێویستی بە پەیوەندی ئینتەرنێت هەیە.",
  "currencyOptionConvert": "گۆڕینی دراو",
  "currencyOptionFavorites": "دراوە دڵخوازەکان",
  "currencyFavoritesTitle": "دڵخوازەکان",
  "currencyFavoritesEmpty": "هێشتا هیچ دراوێکی دڵخواز نییە",
  "currencyFavoritesEmptyHint": "ئەستێرەکە لەسەر هەر دراوێک دابگرە بۆ زیادکردنی لێرە",
  "currencyOptionCustomRate": "گۆڕین بە نرخی تایبەت",
  "customRateTitle": "گۆڕین بە نرخی تایبەت",
  "customRateFieldLabel": "نرخی ئاڵوگۆڕ",
  "currencyRatesTitle": "نرخەکانی دراو",
  "currencyRatesSearchPlaceholder": "گەڕان بە دراو یان کۆد",
  "currencyRatesEmpty": "هیچ دراو دۆز نەکرا",
  "currencyRatesLoading": "بارکردنی نرخەکان...",
  "recentlyDeletedTitle": "نوێترین سڕدراوەکان",
  "emptyNotesText": "هێشتا هیچ تێبینییەک نییە",
  "emptyNotesAction": "+ تێبینی نوێ",
  "searchNotesPlaceholder": "گەڕان لەناو تێبینییەکان...",
  "recentNotesLabel": "نوێترین",
  "sortNewest": "نوێترین",
  "sortOldest": "کۆنترین",
  "sortAz": "ئا–ز",
  "renameNote": "گۆڕینی ناو",
  "duplicateNote": "کۆپیکردن",
  "pinNote": "پینکردن",
  "unpinNote": "لابردنی پین",
  "noteMoreActions": "کردارە زیاترەکان",
  "noteNamePrompt": "ناوی تێبینی:",
  "noteEmptyName": "ناوی تێبینی نابێت بەتاڵ بێت.",
  "copySuffix": " (کۆپی)",
  "noNotesFound": "هیچ تێبینی دۆز نەکرا",
  "createFirstNote": "یەکەم تێبینیت دروست بکە",
  "updatedToday": "ئەمڕۆ نوێکراوە",
  "updatedYesterday": "دوێنێ نوێکراوە",
  "updatedDaysAgo": "{n} ڕۆژ پێش ئێستا نوێکراوە",
  "notePinnedToast": "تێبینی پینکرا",
  "noteUnpinnedToast": "پینی تێبینی لابرا",
  "noteTextStyleLabel": "شێوازی دەق",
  "noteStyleNormalLabel": "دەق",
  "noteBasicLabel": "بنەرایی",
  "noteAlignLabel": "ڕێکخستن",
  "noteFontSizeLabel": "قەبارەی فۆنت",
  "noteFontSmallLabel": "بچووک",
  "noteFontNormalLabel": "ئاسایی",
  "noteFontLargeLabel": "گەورە",
  "noteColorsLabel": "ڕەنگەکان",
  "notePresetsLabel": "پێشڕێکخستنەکان",
  "presetSimple": "ئاسان",
  "presetAcademic": "ئەکادیمی",
  "presetBusiness": "بازرگانی",
  "presetEngineering": "ئەندازیاری",
  "presetModern": "مۆدێرن",
  "noteStylesLabel": "شێوازەکان",
  "noteStyleSimple": "ئاسان",
  "noteStyleAcademic": "ئەکادیمی",
  "noteStyleBusiness": "بازرگانی",
  "noteStyleEngineering": "ئەندازیاری",
  "noteStyleModern": "مۆدێرن",
  "noteStyleNone": "هیچ",
  "noteFramesLabel": "چارچێوە",
  "noteFrameNone": "هیچ",
  "noteFrameClassic": "کلاسیک",
  "noteFrameDashed": "هێڵی بشکاو",
  "noteFrameSoft": "نەرم",
  "pdfExportTitle": "دەرهێنانی PDF",
  "pdfExportStyle": "شێواز",
  "pdfExportTitleLabel": "ناونیشان",
  "pdfExportTitlePh": "ناونیشانی تێبینی (هەڵبژارە)",
  "pdfExportDate": "بەروار",
  "pdfExportCompany": "پڕۆفایلی کۆمپانیا بەکاربهێنە",
  "pdfExportPreview": "پێشبینین",
  "pdfExportCreate": "دروستکردنی PDF",
  "pdfExportClose": "داخستنی دەرگەی دەرهێنان",
  "noteSavedLabel": "پاشەکەوتکرا ✓",
  "emptyDeletedText": "هیچ تێبینی سڕدراو نییە",
  "deleteConfirmTitle": "بە تەواوی بسڕەوە؟",
  "deleteConfirmText": "ئەم کردارە ناتوانرێت بەگەڕبکەیتەوە.",
  "cancelBtn": "هەڵوەشاندنەوە",
  "deletePermanentBtn": "سڕینەوە",
  "doneBtn": "تەواو",
  "deleteNoteBtn": "سڕینەوەی تێبینی",
  "restoreBtn": "گەڕاندنەوە",
  "unfiled": "بێ فۆڵدەر",
  "folderNamePrompt": "ناوی فۆڵدەر:",
  "folderEmptyName": "ناوی فۆڵدەر نابێت بەتاڵ بێت.",
  "folderDuplicateName": "فۆڵدەرێک بەم ناوەکە پێشتر هەیە.",
  "renameFolder": "گۆڕینی ناوی فۆڵدەر",
  "deleteFolder": "سڕینەوەی فۆڵدەر",
  "folderDeleteConfirmTitle": "فۆڵدەرەکە بسڕەوە؟",
  "helpTitle": "یارمەتی و دەربارەی بەرنامە",
  "helpSubtitle": "فێربە کە دەتوانیت چۆن EQ7 بەکارببەیت و تایبەتمەندییەکانت دۆز بکەیتەوە.",
  "helpAboutTitle": "دەربارەی بەرنامەکە",
  "helpAboutDesc": "EQ7 حیسابکەرییەکی ژیر، گشتییە کە بیرکاری ژمارەی ڕۆژانە، ئامرازە زانستی و سەدا، گۆڕینی دراو و زۆر شتی تر لەناو یەک بەرنامەی ئاسان، بەکارهێنانی سادەدا تێکەڵ دەکات.",
  "helpWhyTitle": "بۆچی EQ7 دروستکرا؟",
  "helpWhyDesc": "بیرۆکەکە ئاسانە: یەک حیسابکەر لەجیاتی زۆر حیسابکەر، بۆ خێرایی، ڕوونی و بەکارهێنانی ڕۆژانە دروستکراوە.",
  "helpWhyL1": "حیسابی خێرای ڕۆژانە",
  "helpWhyL2": "ئامرازە زانستییەکان وەک ڕەگی چوارگۆشە، توان و باڕانتیز",
  "helpWhyL3": "حیسابکردنی ئاسانی سەدا",
  "helpWhyL4": "گۆڕینی دراو و نرخە ڕاستەوخۆییەکان",
  "helpWhyL5": "تێبینییەکان و مێژووی حیسابکردن",
  "helpWhyL6": "ئاسان، ڕوون و خێرا لە بەکارهێنان",
  "helpWhyL7": "وەک بەرنامەیەکی دامەزراندنکراو (PWA) لەسەر ئامێرە جیاوەکان کاردەکات",
  "helpSectionsTitle": "ڕونکردنەوەی بەشی بەرنامەکە",
  "helpSecGeneralTitle": "حیسابکەری گشتی",
  "helpSecGeneralDesc": "حیسابکەری سەرەکی بۆ کردارە ڕۆژانەییەکان: کۆکردنەوە، دەرکردن، لێکدان و دابەشکردن.",
  "helpSecGeneralEx": "نموونە: 12 + 7 = 19.",
  "helpSecScientificTitle": "ئامرازە زانستییەکان",
  "helpSecScientificDesc": "\"زانستی\" دابگرە بۆ بەکارهێنانی دوگمەی ڕەگی چوارگۆشە، توان و باڕانتیز لەناو هەمان حیسابکەرەکە.",
  "helpSecScientificEx": "نموونە: √9 = 3، 2^3 = 8.",
  "helpSecPercentTitle": "حیسابکەری سەدا",
  "helpSecPercentDesc": "بە خێرایی سەدایەکی بڕێک لە بەبێ هەنگاوی زیاتری بدۆزەوە.",
  "helpSecPercentEx": "نموونە: ٪15 لە 200 = 30.",
  "helpSecHistoryTitle": "مێژوو",
  "helpSecHistoryDesc": "EQ7 ئەوەی لە ماوەی 24 کاتژمێری ڕابردووت حیسابتکردە، بیری دەکاتەوە بۆ ئەوەی بپێداچوویتەوە یان هاوبەشی بکەیت.",
  "helpSecNotesTitle": "تێبینییەکان",
  "helpSecNotesDesc": "تێبینی خێراکان پاشەکەوتبکە، لەناو فۆڵدەرەکاندا ڕێکیبخە و لە سەرنووسەری تەواوی شاشەدا دەستکاریان بکە.",
  "helpSecCurrencyTitle": "ئامرازەکانی دراو",
  "helpSecCurrencyDesc": "دراوەکان بگەڕە، نرخە ڕاستەوخۆییەکان ببینە، لەنێوان دراوەکاندا بگۆڕە، نرخی تایبەت بەکاربهێنە و دڵخوازەکانت بپارێزە.",
  "helpSecSettingsTitle": "ڕێکخستنەکان",
  "helpSecSettingsDesc": "زمان، ڕوانگە و کاردانەوەی دەنگی بەرنامەکە بە شێوەی خۆت بگۆڕە.",
  "helpButtonsTitle": "چۆنیەتی بەکارهێنانی حیسابکەرەکە",
  "helpBtnNumbers": "دابگرە بۆ نووسینی ژمارەکان.",
  "helpBtnAdd": "ژمارەی دواتری زیاد دەکات.",
  "helpBtnSub": "ژمارەی دواتری دەربدەکات.",
  "helpBtnMul": "بە ژمارەی دواتری لێکی دەکات.",
  "helpBtnDiv": "بە ژمارەی دواتری دابەشی دەکات.",
  "helpBtnEquals": "ئەنجامەکە نیشان دەکات.",
  "helpBtnAc": "هەموو شتێک سڕدەکاتەوە و لە سفرەوە دەستپێدەکات.",
  "helpBtnBack": "دوایین ژمارەکەی کە نووسیتەت سڕدەکاتەوە.",
  "helpBtnDecimal": "خاڵی دەسییەک زیاد دەکات.",
  "helpBtnScientific": "زانستی / سەدا: ئامرازە زیاترەکان دەگرێت و بیان دەگرێت.",
  "helpBtnSpeak": "ئەنجامی ئێستاکە بە دەنگ دەیخوێنێتەوە.",
  "helpSettingsExplainTitle": "ڕێکخستنەکان",
  "helpSetLanguage": "زمان: تەواوی بەرنامەکە لەنێوان زمانە بەردەستەکاندا دەگۆڕێت.",
  "helpSetTheme": "ڕوانگە: شێوازی تور، ڕووناک یان بەنەفش هەڵبژێرە.",
  "helpSetSoundsTitle": "دەنگەکانی بەرنامە: سوییچە سەرەکییەکەی دەنگ و کاردانەوەی هەست.",
  "helpSetSoundsDesc": "کاتێک دەنگەکانی بەرنامە چالاکە، دەنگی دوگمە و لەرینەوە ڕێگەپێدراوە. کوژاندنەوەکەی دەنگەکانەکە خاو دەکات و دووبارە چالاککردنەوەکەی ڕێگەی پێدەکات.",
  "helpSetSoundsSpeech": "قسەکردن/TTS جیا لە دەنگەکانی بەرنامەیە و لەلایەن کوژاندنەوەی دەنگەکانەکوە ناکوژرێتەوە.",
  "helpCurrencyTitle": "گۆڕەری دراو",
  "helpCurrencyDesc": "دراوەکەی کە لەسەرەتە (لە) و ئەوەی کە دەتەوێت (بۆ) هەڵبژێرە، دوای ئەوە بڕێک بنووسە.",
  "helpCurrencySwap": "دوگمەی ئاڵوگۆڕ بەکاربهێنە بۆ پێچەوانەکردنی دوو دراوەکە.",
  "helpCurrencyFavorites": "ئەستێرەکە بەکاربهێنە بۆ نیشانەکردنی دراوێک وەک دڵخواز، و لە لێستەی دراوەکانەوە دڵخوازەکان بکەرەوە.",
  "helpCurrencyCustomRate": "گۆڕین بە نرخی تایبەت ڕێگات دەکات بۆ ناوەکانت خۆت بنووسیت.",
  "helpCurrencyLive": "نرخە ڕاستەوخۆییەکان لە ڕاژەی ئۆنلاینەوە دێن؛ ئەگەر بەردەست نەبوون، ڕەنگە نرخە پاشەکەوتکراوەکان بەکاربهێنرێن.",
  "helpInstallTitle": "دامەزراندن و ئۆفلاین",
  "helpInstallDesc1": "دەتوانیت EQ7 وەک بەرنامەیەک لەسەر ئامێرە پشتگیرکراوەکاندا دامەزەری.",
  "helpInstallDesc2": "هەندێک لە تایبەتمەندییەکان بە بەکارهێنانی سەرچاوە پاشەکەوتکراوەکان بە شێوەی ئۆفلاین کاردەکەن، بەڵام نرخە ڕاستەوخۆییەکان و نوێکردنەوەکانی بەرنامە پێویستی بە پەیوەندی ئینتەرنێت هەیە.",
  "helpBenefitsTitle": "بۆچی EQ7 بەکاربهێنیت؟",
  "helpBenefit1": "حیسابکەری هەموو لەناو یەک",
  "helpBenefit2": "حیسابی خێرای ڕۆژانە",
  "helpBenefit3": "ئامرازە زانستی و سەدا",
  "helpBenefit4": "گۆڕینی دراو",
  "helpBenefit5": "مێژوو و تێبینییەکان",
  "helpBenefit6": "ڕووکاری فرەزمان",
  "helpBenefit7": "شێوازی وەڵامدەر و پشتگیری PWA",
  "helpLangTitle": "زمانەکان",
  "helpLangDesc": "EQ7 بە تەواوی وەرگێڕدراوە. زمانەکەت لە باڕی سەرەکی یان لە ڕێکخستنەکاندا هەڵبژێرە، و تەواوی بەرنامەکە — لەگەڵ ئەم پەڕەی یارمەتییەوە — دەستبەجێ نوێدەکاتەوە.",
  "smartTemplatesSimpleAgreement": "ڕێکەوتنامەی ئاسان",
  "smartTemplatesPaymentReceipt": "وەسڵی پارەدان",
  "smartTemplatesRentalAgreement": "ڕێکەوتنامەی کرێ",
  "smartTemplatesMyTemplates": "قاڵبەکانی من",
  "smartScanCapture": "گرتن",
  "smartScanUploadFallback": "لەجیاتی ئەوە وێنەیەک لە ئامێرەکەت هەڵبژێرە",
  "smartScanDetecting": "دۆزینەوەی بەڵگە",
  "smartScanCorrecting": "ڕاستکردنەوەی وێنە",
  "smartScanImproving": "باشترکردنی وێنە",
  "smartScanReading": "خوێندنەوەی دەق",
  "smartScanProcessing": "پرۆسێسکردن...",
  "smartScanReviewTitle": "پێداچوونەوەی ئەنجامی ناسینەوە",
  "smartScanPreviewLabel": "بەڵگەی پرۆسێسکراو",
  "smartUntitledDoc": "بەڵگەی بێ ناونیشان",
  "smartBlankNavOf": "لە",
  "smartPdfSave": "پاشەکەوتکردنی PDF",
  "currencyRatesError": "نرخەکان بەردەست نین",
  "folderDeleteConfirmText": "تێبینییەکانی ناو ئەم فۆڵدەرە دەگوازرێنەوە بۆ بەشی بێ فۆڵدەر و دەپارێزرێن."
};