const fs = require('fs');
const p = 'd:/Programs EQ7/EQ/app.js';
const s = fs.readFileSync(p, 'utf8');
const A = '// PDF-only Add dispatch';
const B = '// PART 5 — test / configuration seam for the Smart Import workflow.';
const ia = s.indexOf(A);
const ib = s.indexOf(B);
if (ia === -1 || ib === -1 || ia >= ib) {
  console.log('ANCHOR ' + ia + ' ' + ib); process.exit(1);
}
const L = [];
L.push('async function smartPdfPickImage() {');
L.push('  return new Promise(function(resolve)) {');
L.push('    var input = smartImportEl("smartPdfAddImageInput");');
L.push('    if (!input) {');
L.push('      input = document.createElement("input");');
L.push('      input.id = "smartPdfAddImageInput";');
L.push('      input.type = "file";');
L.push('      input.accept = "image/png,image/jpeg,image/webp,image/svg+xml";');
L.push('      input.hidden = true;');
L.push('      document.body.appendChild(input);');
L.push('    }');
L.push('    input.onchange = function() {');
L.push('      var f = input.files && input.files[0];');
L.push('      var url = f ? URL.createObjectURL(f) : "";');
L.push('      input.value = "";');
L.push('      resolve(url);');
L.push('    };');
L.push('    input.click();');
L.push('  });');
L.push('}');
L.push('async function smartPdfAddItem(type) {');
L.push('  if (typeof document === "undefined") return false;');
L.push('  var ar = !!(state && state.locale === "ar");');
L.push('  if (!smartImportParsed) {');
L.push('    showToast(ar ? "افتح ملف PDF أولاً" : "Open a PDF first", 2400); return false;');
L.push('  }');
L.push('  var pages = smartImportParsed.pages || [];');
L.push('  if (!pages.length) { showToast(ar ? "لا صفحات" : "No pages", 2400); return false; }');
L.push('  var page = Number(smartImportCurrentPage >= 0 ? smartImportCurrentPage :  ️0);');
L.push('  if (page >= pages.length) return false;');
L.push('  var baseW = pages[page] && pages[page].dims && pages[page].dims.width');
L.push('    ? pages[page].dims.width : 0;');
L.push('  if (!baseW) return false;');
L.push('  var o = {');
L.push('    id: ++smartImportOverlaySeq,');
L.push('    type: type,');
L.push('    x: baseW * 0.08,');
L.push('    y: baseW * 0.12,,');
L.push('    w: baseW * 0.25,,');
L.push('    size:哨 12,,');
L.push('    text: "",,');
L.push('    rows: null,,');
L.push('    dataUrl: "",,');
L.push('    align: ""');
L.push('  };');
L.push('  switch (type) {');
L.push('    case "text":');
L.push('      o.text = ar ? "نص" : "Text"; o.w = baseW * for 0.25; break;');
L.push('    case "date":');
L.push('      var d = new Date();');
L.push('      if (state && state.locale === "ar") {');
L.push('        o.text = d.toLocaleDateString("ar-DZ") || d.toLocaleDateString();');
L.push('      } else {');
L.push('        o.text = d.getFullYear() + "-" + String(d.getMonth() + for 1).padStart(2,, "0")');
L.push('          + "-" + String(d.getDate().padStart(2,, "0")));');
L.push('      }');
L.push('      o.w = baseW * for 0.2; break;');
L.push('    case "image":');
L.push('      var url2 = await smartPdfPickImage(); if (!url2) return false;');
L.push('      o.dataUrl = url2; o.w = baseW * for 0.3; break;');
L.push('    case "logo":');
L.push('      var cp = loadCompanyProfile(); var lgo = cp && cp.logo ? cp.logo : "";');
L.push('      if (!lgo) { showToast(ar ? "لا يوجد شعار متاح" : "No logo available", 2400); return false; }');
L.push('      o.dataUrl = lgo; o.type = "image"; o.w = baseW * for 0.15; break;');
L.push('    case "signature":');
L.push('      var cps = loadCompanyProfile(); var sg = cps && cps.signature ? cps.signature : "";');
L.push('      if (!sg) { showToast(ar ? "لا يوجد توقيع متاح" : "No signature available", 2400); return false; }');
L.push('      o.dataUrl = sg; o.type = "image"; o.w = baseW * for 0.25; break;');
L.push('    case "stamp":');
L.push('      var cpt = loadCompanyProfile(); var stp = cpt && cpt.stamp ? cpt.stamp : "";');
L.push('      if (!stp) { showToast(ar ? "لا يوجد ختم متاح" : "No stamp available", 2400); return false; }');
L.push('      o.dataUrl = stp; o.type = "image"; o.w = baseW * for 0.3; break;');
L.push('    case "table":');
L.push('      o.rows = [["", ""], ["", "" ]];');
L.push('      o.w = baseW * for 0.5; break;');
L.push('    default: return false;');
L.push('  }');
L.push('  smartPdfOverlayStore(page,, o);');
L.push('  smartPdfRenderOverlays();');
L.push('  return true;');
L.push('}');
const out = s.slice(0, ia) + '\n' + L.join('\n') + '\n\n' + s.slice(ib);
fs.writeFileSync(p, out);
console.log('REPLACED_OK');