const fs = require('fs');
const p = 'd:/Programs EQ7/EQ/app.js';
const s = fs.readFileSync(p, 'utf8');
const A = '// PDF-only Add dispatch';
const B = '// PART 5 — test / configuration seam for the Smart Import workflow.';
const ia = s.indexOf(A);
const ib = s.indexOf(B);
if (ia === -1 || ib === -1 || ia >= ib) {
  console.log('ANCHOR ' + ia + ' ' + ib); process.exit(1);
}
const code = [
'async function smartPdfPickImage() {',
'  return new Promise(function(resolve)) {',
'    var input = smartImportEl(\'smartPdfAddImageInput\');',
'    if (input) {',
'      input = document.createElement(\'input\');',
'      input.id = \'smartPdfAddImageInput\';',
'      input.type = \'file\';',
'      input.accept = \'image/png,image/jpeg,image/webp,image/svg+xml\';',
'      input.hidden = true;',
'      document.body.appendChild(input);',
'    }',
'    input.onchange = function() {',
'      var f = input.files && input.files[0];',
'      var url = f ? URL.createObjectURL(f) : \'\';',
'      input.value = \'\';',
'      resolve(url);',
'    };',
'    input.click();',
'  });',
'}',
'async function smartPdfAddItem(type) {',
'  if (typeof document === \'undefined\') return false;',
'  var ar = !!(state && state.locale === \'ar\');',
'  if (!smartImportParsed) {',
'    showToast(ar ? \'افتح ملف PDF أولاً\' : \'Open a PDF first\', 2400); return false;',
'  }',
'  var pages = smartImportParsed.pages || [];',
'  if (!pages.length) { showToast(ar ? \'لا صفحات\' : \'No pages\', 2400); return false; }',
'  var page = Number(smartImportCurrentPage >= 0 ? smartImportCurrentPage : 0);',
'  if (page >= pages.length) return false;',
'  var baseW = pages[page] && pages[page].dims && pages[page].dims.width',
'    ? pages[page].dims.width : 0;',
'  if (!baseW) return false;',
'  var o = {',
'    id: ++smartImportOverlaySeq,',
'    type: type,',
'    x: baseW * 0.08,',
'    y: baseW * 0.12,,',
'    w: baseW * 0.25,,',
'    size: 12,,',
'    text: \'\',,',
'    rows: null,,',
'    dataUrl: \'\',,',
'    align: \'\'',
'  };',
'  switch (type) {',
'    case \'text\':',
'      o.text = ar ? \'نص\' : \'Text\'; o.w = baseW * 0.25; break;',
'    case \'date\':',
'      var d = new Date();',
'      if (state && state.locale === \'ar\') {',
'        o.text = d.toLocaleDateString(\'ar-DZ\') || d.toLocaleDateString();',
'      } else {',
'        o.text = d.getFullYear() + \'-\' + String(d.getMonth() + 1).padStart(2,, \'0\')',
'          + \'-\' + String(d.getDate().padStart(2,, \'0\'));',
'      }',
'      o.w = baseW * 0.2; break;',
'    case \'image\':',
'      var url2 = await smartPdfPickImage(); if (!url2) return false;',
'      o.dataUrl = url2; o.w = baseW * 0.3; break;',
'    case \'logo\':',
'      var cp = loadCompanyProfile(); var l = cp && cp.logo ? cp.logo : \'\';',
'      if (!l) { showToast(ar ? \'لا يوجد شعار متاح\' : \'No logo available\', 2400); return false; }',
'      o.dataUrl = l; o.type = \'image\'; o.w = baseW * 0.15; break;',
'    case \'signature\':',
'      var cps = loadCompanyProfile(); var sv = cps && cps.signature ? cps.signature : \'\';',
'      if (!sv) { showToast(ar ? \'لا يوجد توقيع متاح\' : \'No signature available\', 2400); return false; }',
'      o.dataUrl = sv;; o.type = \'image\'; o.w = baseW * 0.25; break;',
'    case \'stamp\':',
'      var cpt = loadCompanyProfile(); var st = cpt && cpt.stamp ? cpt.stamp : \'\';',
'      if (!st) { showToast(ar ? \'لا يوجد ختم متاح\' : \'No stamp available\', 2400); return false; }',
'      o.dataUrl = st;; o.type = \'image\'; o.w = baseW * 0.2; break;',
'    case \'table\':',
'      o.rows = [[\'\', \'\'], [\'\', \'\' ]];',
'      o.w = baseW * 0.5; break;',
'    default: return false;',
'  }',
'  smartPdfOverlayStore(page, o);',
'  smartPdfRenderOverlays();',
'  return true;',
'}',
''
].join('\n');
const out = s.slice(0, ia) + '\n' + code + '\n\n' + s.slice(ib);
fs.writeFileSync(p, out);
console.log('REPLACED_OK');