const fs = require('fs');
const p = 'd:/Programs EQ7/EQ/app.js';
let s = fs.readFileSync(p, 'utf8');
const b = s;
const saveAnchor = "  const out = await doc.save({ useObjectStreams: false, updateMetadata: false });";
if (s.split(saveAnchor).length !== 2) throw new Error('save anchor');
const OV = [
  "  // PART 22 - draw the added overlay elements (Text/Image/Logo/Signature/Stamp/Date/Table)",
  "  // as REAL PDF content via pdf-lib. Original content is preserved; result is a NEW blob.",
  "  try {",
  "    const ovByPage = overlaysByPage || {};",
  "    if (Object.keys(ovByPage).length) {",
  "      let helv = null;",
  "      try { helv = await doc.embedFont(pdfLib.StandardFonts.Helvetica); } catch (e) { helv = null; }",
  "      for (const pk in ovByPage) {",
  "        const pi = parseInt(pk, 10);",
  "        if (!isFinite(pi) || pi < 0 || pi >= doc.getPageCount()) continue;",
  "        const pageObj = doc.getPage(pi);",
  "        const meta = (pages && pages[pi]) || null;",
  "        const dimW = (meta && meta.dims && meta.dims.width) || 0;",
  "        if (!dimW) continue;",
  "        const f = pageObj.getWidth() / dimW;",
  "        const H = pageObj.getHeight();",
  "        const list = ovByPage[pk] || [];",
  "        for (const o of list) {",
  "          if (!o) continue;",
  "          const x = o.x * f;",
  "          const yTop = o.y * f;",
  "          try {",
  "            if (o.type === 'text' || o.type === 'date') {",
  "              const size = Math.max(6, (o.size || 12) * f);",
  "              const txt = String(o.text || '');",
  "              if (txt && helv) pageObj.drawText(txt, { x: x, y: H - yTop - size, size: size, font: helv, color: pdfLib.rgb(0, 0, 0) });",
  "            } else if (o.type === 'table') {",
  "              const rows = Array.isArray(o.rows) ? o.rows : [];",
  "              const size = Math.max(6, 12 * f);",
  "              const colW = ((o.w || 200) * f) / 2;",
  "              const rowH = size * 1.6;",
  "              let yy = H - yTop;",
  "              for (const row of rows) {",
  "                let xx = x;",
  "                const cells = Array.isArray(row) ? row : [];",
  "                for (const cell of cells) {",
  "                  pageObj.drawRectangle({ x: xx, y: yy - rowH, width: colW, height: rowH, borderColor: pdfLib.rgb(0.2, 0.2, 0.2), borderWidth: 1 });",
  "                  const ct = String(cell || '');",
  "                  if (ct && helv) pageObj.drawText(ct, { x: xx + 3, y: yy - rowH + size * 0.35, size: size, font: helv, color: pdfLib.rgb(0, 0, 0) });",
  "                  xx += colW;",
  "                }",
  "                yy -= rowH;",
  "              }",
  "            } else if (o.type === 'image' && o.dataUrl) {",
  "              const m = /^data:image\\/(png|jpeg|jpg|webp|svg\\+xml);base64,/.exec(o.dataUrl);",
  "              if (m) {",
  "                const b64 = o.dataUrl.slice(m[0].length);",
  "                const bin = atob(b64);",
  "                const u8 = new Uint8Array(bin.length);",
  "                for (let k = 0; k < bin.length; k++) u8[k] = bin.charCodeAt(k) & 0xff;",
  "                let img = null;",
  "                if (m[1] === 'png') img = await doc.embedPng(u8);",
  "                else if (m[1] === 'jpeg' || m[1] === 'jpg') img = await doc.embedJpg(u8);",
  "                if (img) {",
  "                  const w = (o.w || 120) * f;",
  "                  const h = w * (img.height / Math.max(1, img.width));",
  "                  pageObj.drawImage(img, { x: x, y: H - yTop - h, width: w, height: h });",
  "                }",
  "              }",
  "            }",
  "          } catch (e) { /* additive overlay skipped */ }",
  "        }",
  "      }",
  "    }",
  "  } catch (e) { /* overlays are additive */ }",
  saveAnchor
].join('\n');
s = s.replace(saveAnchor, OV);
if (s !== b) fs.writeFileSync(p, s);
console.log('FIXB1 OK CHANGED=' + (s !== b));