const fs = require('fs');
const p = 'd:/Programs EQ7/EQ/__notes_test/p23_harness.mjs';
const T = [];
T.push("// --- export: genuine PDF, real text, original untouched ---");
T.push("const exp = await page.evaluate(async () => { const blob = await window.__smartImport.editedBlob(); const buf = new Uint8Array(await blob.arrayBuffer()); let bin = ''; for (let i = 0; i < buf.length; i++) bin += String.fromCharCode(buf[i]); return { b64: btoa(bin), head: bin.slice(0, 5), size: buf.length }; });");
T.push("check('P23-33 exported file is a genuine PDF (%PDF-)', exp.head === '%PDF-' && exp.size > 1000, { head: exp.head, size: exp.size });");
T.push("const extracted = await page.evaluate(async (b64) => {");
T.push("  let pdfjs = window.pdfjsLib;");
T.push("  if (!pdfjs) { await new Promise((res, rej) => { const sc = document.createElement('script'); sc.src = '/__pdfdiag/vendor/pdf.min.js'; sc.onload = res; sc.onerror = rej; document.head.appendChild(sc); }); pdfjs = window.pdfjsLib; }");
T.push("  if (pdfjs.GlobalWorkerOptions) pdfjs.GlobalWorkerOptions.workerSrc = '/__pdfdiag/vendor/pdf.worker.min.js';");
T.push("  const bin = atob(b64); const u8 = new Uint8Array(bin.length); for (let i = 0; i < bin.length; i++) u8[i] = bin.charCodeAt(i);");
T.push("  const doc = await pdfjs.getDocument({ data: u8 }).promise;");
T.push("  const p1 = await (await doc.getPage(1)).getTextContent();");
T.push("  const p2 = await (await doc.getPage(2)).getTextContent();");
T.push("  return { pages: doc.numPages, t1: p1.items.map((i) => i.str).join(' '), t2: p2.items.map((i) => i.str).join(' ') };");
T.push("}, exp.b64);");
T.push("check('P23-34 exported PDF keeps 2 pages (multi-page intact)', extracted.pages === 2, extracted.pages);");
T.push("check('P23-35 table-1 cell text is REAL selectable PDF text on page 1', ['Item', 'Quantity', 'Price', '50', '25'].every((w) => extracted.t1.indexOf(w) >= 0), extracted.t1.slice(0, 140));");
T.push("check('P23-36 table-2 cell text is REAL selectable PDF text on page 2', extracted.t2.indexOf('PAGE2TBL') >= 0, extracted.t2.slice(0, 100));");
T.push("check('P23-37 original page content intact after export', extracted.t2.indexOf('Page 2') >= 0, extracted.t2.slice(0, 60));");
T.push("const origHash2 = crypto.createHash('sha256').update(fs.readFileSync(FIXTURE)).digest('hex');");
T.push("check('P23-38 original source PDF unchanged (sha256)', origHash2 === origHash);");
T.push("const notesAfter = await page.evaluate(() => localStorage.getItem('eq-notes-data') || localStorage.getItem('notesData') || '');");
T.push("const profAfter = await page.evaluate(() => localStorage.getItem('eq-note-company-profile') || '');");
T.push("check('P23-39 Notes storage unchanged', notesAfter === notesBefore);");
T.push("check('P23-40 Company Profile storage unchanged', profAfter === profBefore, { seeded: profBefore !== '' });");
fs.appendFileSync(p, T.join('\n') + '\n');
console.log('TAIL PART3 OK');
