const fs = require('fs');
const p = 'd:/Programs EQ7/EQ/__notes_test/p23_harness.mjs';
const T = [];
T.push("// --- responsive: table + toolbar usable, no new UI overflow ---");
T.push("const resp = [];");
T.push("for (const w of [1366, 768, 430, 390]) {");
T.push("  await page.setViewport({ width: w, height: 850 });");
T.push("  await sleep(300);");
T.push("  const r = await page.evaluate(() => {");
T.push("    const holder = document.getElementById('smartPdfEditor');");
T.push("    const bar = document.querySelector('#smartPdfEditor .smart-pdf-ov-table .smart-pdf-tbar');");
T.push("    const btn = bar ? bar.querySelector('[data-tact=\"row+\"]') : null;");
T.push("    const br = bar ? bar.getBoundingClientRect() : null;");
T.push("    return { bar: !!bar, btn: !!btn, barInX: br ? (br.left >= -4 && br.right <= window.innerWidth + 4) : true, hx: holder.scrollWidth - holder.clientWidth };");
T.push("  });");
T.push("  resp.push({ w, ...r });");
T.push("}");
T.push("check('P23-41 table controls present + inside viewport at 1366/768/430/390', resp.every((r) => r.bar && r.btn && r.barInX), resp.map((r) => r.w + ':' + (r.bar ? 'bar' : 'NO')).join(' '));");
T.push("check('P23-42 no new editor-holder overflow caused by PART 23', resp.every((r) => r.hx <= 0), resp.map((r) => r.w + ':hx' + r.hx).join(' '));");
T.push("// --- RTL: reload with Arabic, reopen the editor, check Arabic labels ---");
T.push("await page.evaluate(() => { localStorage.setItem('eq-language', 'ar'); });");
T.push("await page.reload({ waitUntil: 'load' }); await sleep(900);");
T.push("await openPdfEditor();");
T.push("await addViaMenu('table'); await sleep(400);");
T.push("const rtl = await page.evaluate(() => {");
T.push("  const html = document.documentElement;");
T.push("  const bar = document.querySelector('#smartPdfEditor .smart-pdf-tbar');");
T.push("  const btn = bar && bar.querySelector('[data-tact=\"row+\"]');");
T.push("  const del = bar && bar.querySelector('[data-tact=\"row-\"]');");
T.push("  return { dir: html.getAttribute('dir'), rowLabel: btn ? (btn.getAttribute('title') || '') : '', delLabel: del ? (del.getAttribute('aria-label') || '') : '' };");
T.push("});");
T.push("check('P23-43 RTL mode + Arabic accessible table labels from existing i18n', rtl.dir === 'rtl' && rtl.rowLabel.indexOf('\\u0635\\u0641') >= 0 && rtl.delLabel.length > 0, rtl);");
T.push("await page.evaluate(() => { localStorage.setItem('eq-language', 'en'); });");
T.push("await page.reload({ waitUntil: 'load' }); await sleep(900);");
T.push("await openPdfEditor();");
T.push("await addViaMenu('table'); await sleep(400);");
T.push("const ltr = await page.evaluate(() => { const bar = document.querySelector('#smartPdfEditor .smart-pdf-tbar'); const btn = bar && bar.querySelector('[data-tact=\"row+\"]'); return { label: btn ? (btn.getAttribute('title') || '') : '' }; });");
T.push("check('P23-44 LTR mode + English accessible labels', /row/i.test(ltr.label), ltr);");
T.push("// --- results ---");
T.push("check('P23-45 no new JS errors', realErrs.length === 0, realErrs.slice(0, 3));");
T.push("await browser.close();");
T.push("server.close();");
T.push("fs.writeFileSync(path.join(HERE, 'p23_results.txt'), LOG.join('\\n') + '\\nRESULTS_JSON=' + JSON.stringify({ pass, fail, not_verified: notVerified, preexisting }) + '\\nERRORS=' + JSON.stringify(realErrs) + '\\n');");
T.push("console.log('DONE p=' + pass + ' f=' + fail + ' nv=' + notVerified + ' pre=' + preexisting);");
fs.appendFileSync(p, T.join('\n') + '\n');
console.log('TAIL PART4 OK');
