const fs = require('fs');
const p = 'd:/Programs EQ7/EQ/__notes_test/p23_harness.mjs';
const T = [];
T.push("await selectCell(0, 0);");
T.push("await tbar('tc', 1); await sleep(200);");
T.push("let m1 = await tableModel();");
T.push("check('P23-19 text color applies to the selected cell', m1.rows[0][0].color === '#ff0000', m1.rows[0][0].color);");
T.push("await tbar('bg', 0); await sleep(200);");
T.push("m1 = await tableModel();");
T.push("check('P23-20 cell background applies to the selected cell', m1.rows[0][0].bg === '#ffff00', m1.rows[0][0].bg);");
T.push("await tbar('bc', 1); await sleep(200);");
T.push("m1 = await tableModel();");
T.push("check('P23-21 border color applies to the table model', m1.borderColor === '#ff0000', m1.borderColor);");
T.push("await tbar('bn'); await sleep(200);");
T.push("m1 = await tableModel();");
T.push("const domNob = await page.evaluate(() => !!document.querySelector('#smartPdfEditor .smart-pdf-ov-table table[style*=\"--tdbw:0px\"]'));");
T.push("check('P23-22 border toggle off (model + preview)', m1.hasBorder === false && domNob, { hasBorder: m1.hasBorder, domNob });");
T.push("await tbar('by'); await sleep(200);");
T.push("m1 = await tableModel();");
T.push("check('P23-23 border toggle back on', m1.hasBorder !== false, m1.hasBorder);");
T.push("await selectCell(0, 1);");
T.push("await tbar('f-b'); await tbar('f-i'); await sleep(200);");
T.push("m1 = await tableModel();");
T.push("check('P23-24 bold + italic apply to the selected cell', m1.rows[0][1].bold === true && m1.rows[0][1].italic === true, m1.rows[0][1]);");
T.push("await tbar('al-c'); await sleep(200);");
T.push("m1 = await tableModel();");
T.push("check('P23-25 center alignment applies', m1.rows[0][1].align === 'center', m1.rows[0][1].align);");
T.push("await tbar('al-r'); await sleep(150); m1 = await tableModel();");
T.push("check('P23-26 right alignment applies', m1.rows[0][1].align === 'right', m1.rows[0][1].align);");
T.push("await tbar('al-l'); await sleep(150); m1 = await tableModel();");
T.push("check('P23-27 left alignment applies', m1.rows[0][1].align === 'left' || m1.rows[0][1].align === '', m1.rows[0][1].align);");
T.push("await selectCell(0, 0);");
T.push("await tbar('rh+'); await tbar('rh+'); await tbar('rh-'); await sleep(200);");
T.push("m1 = await tableModel();");
T.push("check('P23-28 row-height control clamps within valid range', m1.rowH === undefined || m1.rowH >= 12, m1.rowH);");
fs.appendFileSync(p, T.join('\n') + '\n');
console.log('TAIL PART2a OK');
