const fs = require('fs');
const p = 'd:/Programs EQ7/EQ/__notes_test/p23_harness.mjs';
const T = [];
T.push("// --- page association + multi-page separation ---");
T.push("const page0Table = await page.evaluate(() => document.querySelector('#smartPdfEditor .smart-pdf-ov-table').dataset.page);");
T.push("await page.evaluate(() => { const wrap = document.querySelector('#smartPdfEditor .smart-pdf-page[data-page=\"1\"]'); wrap.dispatchEvent(new PointerEvent('pointerdown', { bubbles: true, clientX: 10, clientY: 10 })); });");
T.push("await addViaMenu('table'); await sleep(400);");
T.push("const ts2 = await tables();");
T.push("const pgTbl = await page.evaluate(() => { const bs = [...document.querySelectorAll('#smartPdfEditor .smart-pdf-ov-table')]; return bs.map((b) => ({ page: b.dataset.page, hasTbar: !!b.querySelector('.smart-pdf-tbar') })); });");
T.push("check('P23-29 each table stays on its own page (0 vs 1)', ts2.length === 2 && ts2.some((t) => t.page === 0) && ts2.some((t) => t.page === 1) && page0Table === '0', { pages: ts2.map((t) => t.page), pgTbl });");
T.push("check('P23-30 both tables carry their own controls bar', pgTbl.every((t) => t.hasTbar), pgTbl);");
T.push("await setCell2(1, 0, 0, 'PAGE2TBL'); await sleep(200);");
T.push("const pg2 = await tableModel(1);");
T.push("const pg2check = pg2 && pg2.rows && pg2.rows[0] ? pg2.rows[0][0].text : '';");
T.push("check('P23-31 page-2 table edits stay separate from page-1 data', pg2check === 'PAGE2TBL' && (await tableModel(0)).rows[0][0].text === 'Item', pg2check);");
T.push("await page.evaluate(() => { document.body.click(); }); await sleep(300);");
T.push("const visT = await page.evaluate(() => [...document.querySelectorAll('#smartPdfEditor .smart-pdf-ov-table table')].length);");
T.push("check('P23-32 preview renders both tables after rerender', visT === 2, visT);");
fs.appendFileSync(p, T.join('\n') + '\n');
console.log('TAIL PART2b OK');
