const fs = require('fs');
const p = 'd:/Programs EQ7/EQ/app.js';
let s = fs.readFileSync(p, 'utf8');
const NL = s.includes('\r\n') ? '\r\n' : '\n';
const ANCHOR = "  if (typeof window !== 'undefined' && window.__smartImport) {";
const idx = s.indexOf(ANCHOR);
if (idx === -1) { console.log('ANCHOR NOT FOUND'); process.exit(1); }
const code = [
"// ===== PART 24 — PDF Mark (Highlight / Underline / Draw / Comment) =====",
"  // All annotations live in the SAME smartImportOverlays[page] store the existing",
"  // PDF editor items use. Coordinates are kept in PDF page units and converted",
"  // with the existing smartPdfOverlayScale(); they survive zoom/resize/mobile/re-open.",
"  // No image/screenshot fallbacks.",
"  let smartPdfMarkDrawMode = false;",
"  let smartPdfMarkDrawPage = -1;",
"  let smartPdfMarkDrawCurrent = null;",
"  function smartPdfMarkPageWrap(pg) {",
"    const holder = smartImportEl('smartPdfEditor');",
"    return holder ? holder.querySelector('.smart-pdf-page[data-page=\"' + Number(pg) + '\"]') : null;",
"  }",
"  function smartPdfMarkClientToPage(pg, cx, cy) {",
"    const wrap = smartPdfMarkPageWrap(pg);",
"    if (!wrap) return { x: 0, y: 0 };",
"    let scl = 1; try { scl = smartPdfOverlayScale(); } catch (e) { scl = 1; }",
"    if (!scl || scl <= 0) scl = 1;",
"    const r = wrap.getBoundingClientRect();",
"    return { x: Math.max(0, (cx - r.left) / scl), y: Math.max(0, (cy - r.top) / scl) };",
"  }",
"  function smartPdfMarkSelection() {",
"    if (typeof window === 'undefined' || !window.getSelection) return null;",
"    const sel = window.getSelection();",
"    if (!sel || !sel.rangeCount || sel.isCollapsed) return null;",
"    const pg = Number(smartImportCurrentPage >= 0 ? smartImportCurrentPage : 0);",
"    const wrap = smartPdfMarkPageWrap(pg);",
"    if (!wrap) return null;",
"    let scl = 1; try { scl = smartPdfOverlayScale(); } catch (e) { scl = 1; }",
"    if (!scl || scl <= 0) scl = 1;",
"    const rr = wrap.getBoundingClientRect();",
"    let x0 = 1e18, y0 = 1e18, x1 = -1e18, y1 = -1e18, any = false;",
"    for (let r = 0; r < sel.rangeCount; r++) {",
"      try {",
"        const rc = sel.getRangeAt(r).getBoundingClientRect();",
"        x0 = Math.min(x0, rc.left); y0 = Math.min(y0, rc.top);",
"        x1 = Math.max(x1, rc.right); y1 = Math.max(y1, rc.bottom); any = true;",
"      } catch (e2) {}",
"    }",
"    if (!any || x1 < x0 || y1 < y0) return null;",
"    const pad = 1.2;",
"    return { x: (x0 - rr.left) / scl - pad, y: (y0 - rr.top) / scl - pad, w: (x1 - x0 + pad * 2) / scl, h: (y1 - y0 + pad * 2) / scl, text: String(sel.toString() || '') };",
"  }",
"  function smartPdfMarkT(key, fallback) {",
"    try { return (smartImportT() || {})[key] || fallback; } catch (e) { return fallback; }",
"  }",
"  function smartPdfMarkToast(msg) { try { showToast(msg, 2400); } catch (e) {} }",
"  function smartPdfAddMarkAnnotation(type, data) {",
"    if (typeof document === 'undefined' || !smartImportParsed) return false;",
"    const pages = smartImportParsed.pages || [];",
"    const pg = Number(smartImportCurrentPage >= 0 ? smartImportCurrentPage : 0);",
"    if (pg >= pages.length) return false;",
"    const o = Object.assign({ id: ++smartImportOverlaySeq, type: type, page: pg }, data || {});",
"    smartPdfOverlayStore(pg, o);",
"    smartPdfRenderOverlays();",
"    return true;",
"  }",
"  function smartPdfMarkHighlight() {",
"    const ar = !!(state && state.locale === 'ar');",
"    const r = smartPdfMarkSelection();",
"    if (!r) { smartPdfMarkToast(smartPdfMarkT('smartPdfMarkSelectText', ar ? 'حدد النص أولاً' : 'Select text to mark first')); return false; }",
"    return smartPdfAddMarkAnnotation('highlight', { x: r.x, y: r.y, w: Math.max(4, r.w), h: Math.max(7, r.h), text: r.text, color: '#fde047' });",
"  }",
"  function smartPdfMarkUnderline() {",
"    const ar = !!(state && state.locale === 'ar');",
"    const r = smartPdfMarkSelection();",
"    if (!r) { smartPdfMarkToast(ar ? 'حدد النص أولاً' : 'Select text to mark first'); return false; }",
"    return smartPdfAddMarkAnnotation('underline', { x: r.x, y: r.y + r.h - 1, w: Math.max(4, r.w), color: '#2563eb', text: r.text });",
"  }",
"  function smartPdfMarkClearDraw() {",
"    smartPdfMarkDrawMode = false;",
"    const wp = smartPdfMarkPageWrap(smartPdfMarkDrawPage);",
"    if (wp) { wp.classList.remove('smart-pdf-mark-draw'); const h = wp.querySelector('.smart-pdf-mark-draw-hint'); if (h) h.remove(); const sv = wp.querySelector(':scope > .smart-pdf-mark-draw-svg'); if (sv) sv.remove(); }",
"    smartPdfMarkDrawCurrent = null; smartPdfMarkDrawPage = -1;",
"  }",
"",
].join(NL);
s = s.slice(0, idx) + code + s.slice(idx);
fs.writeFileSync(p, s);
console.log('INSERT OK block1; new size', s.length);