import fs from 'node:fs';
const a = fs.readFileSync('app.js', 'utf8');
const h = fs.readFileSync('index.html', 'utf8');
const c = fs.readFileSync('styles.css', 'utf8');
let fail = 0;
const chk = (n, ok, d='') => { console.log((ok?'PASS':'FAIL')+'  '+n+(d?'  -> '+d:'')); if(!ok) fail++; };
chk('entry drawer action preserved', h.includes('data-action="open-smart-docs"'));
chk('openSmartDocs preserved', a.includes('function openSmartDocs()'));
chk('closeSmartDocs preserved', a.includes('function closeSmartDocs()'));
const modalSeg = h.slice(h.indexOf('id="smartDocsModal"'), h.indexOf('id="drawerOverlay"'));
chk('Upload PDF button in Smart Docs', modalSeg.includes('id="smartPdfUploadBtn"') && modalSeg.includes('Upload PDF'));
chk('file input PDF only', modalSeg.includes('id="smartPdfFileInput"') && modalSeg.includes('accept="application/pdf,.pdf"'));
chk('workspace in Smart Docs', modalSeg.includes('id="smartPdfWorkspace"') && modalSeg.includes('id="smartPdfScroll"') && modalSeg.includes('id="smartPdfPages"'));
chk('no nested modal/iframe preview', !modalSeg.includes('<iframe') && !modalSeg.includes('smartPdfResultModal'));
chk('scoped smartPdf functions', a.includes('function smartPdfOpenFile') && a.includes('function smartPdfRenderAllPages') && a.includes('function smartPdfBuildTextLayer'));
chk('reuses existing pdf.js dep (no new dep)', a.includes('NOTE_PDF_PREVIEW_LIB_URL') && a.includes('ensureNotePdfPreviewLib'));
chk('all pages render (loop to totalPages)', a.includes('n <= smartPdfState.totalPages'));
chk('edit surface aligned (convertToViewportPoint)', a.includes('convertToViewportPoint'));
chk('no forbidden integrations in new code', (()=>{ const s=a.indexOf('function smartPdfEnsureLib'); const e=a.indexOf('function openPdfReportsWorkspace', s); if(s<0||e<0||e<=s) return false; const seg=a.slice(s,e); return !seg.includes('smartPdfShare') && !seg.includes('Whatsapp') && !seg.includes('Telegram') && !seg.includes('Supabase') && !seg.includes('Stripe'); })());
chk('package.json unchanged deps', JSON.parse(fs.readFileSync('package.json','utf8')).dependencies['puppeteer-core'] !== undefined);
chk('css has fullscreen scroll + responsive', c.includes('.smart-pdf-scroll') && c.includes('.smart-pdf-page-stage') && c.includes('@media (max-width: 640px)'));
chk('css brace balance', (()=>{let b=0; for(const ch of c){if(ch==='{')b++; if(ch==='}')b--;} return b===0;})());
chk('Calculator untouched', a.includes('updateSecondaryDisplay') && h.includes('keypad-btn'));
chk('Notes untouched', a.includes('openNotesManager') && h.includes('notesManagerModal'));
chk('PDF Reports untouched', a.includes('openPdfReportsWorkspace') && h.includes('pdfV1Viewer'));
chk('PWA untouched', fs.existsSync('manifest.json'));
console.log(fail===0 ? 'SMART-PDF-PHASE STATIC ALL PASS' : 'SMART-PDF-PHASE STATIC FAILURES: '+fail);
process.exit(fail===0?0:1);
